-- Dev-only sample stories: 15 per topic (45 topics), text only.
-- Load with: psql "$DATABASE_URL" -f backend/seed/dev_stories.sql
-- Idempotent: rows are keyed by stories.dedupe_keys->>'seed'. Remove with:
--   DELETE FROM stories WHERE model = 'seed';
BEGIN;

CREATE TEMP TABLE seed_items (
    id         bigserial PRIMARY KEY,
    topic_slug text NOT NULL,
    title      text NOT NULL,
    summary    text NOT NULL
) ON COMMIT DROP;

INSERT INTO seed_items (topic_slug, title, summary) VALUES
('languages','Language runtimes converge on faster cold starts','Major runtimes ship startup optimizations that cut cold-start latency for CLI tools and serverless functions.'),
('languages','Memory safety guidance gains momentum across ecosystems','New guidance pushes teams toward memory-safe languages for new infrastructure code.'),
('languages','Package managers tighten lockfile verification','Several ecosystems now verify lockfile integrity by default during installs.'),
('languages','Pattern matching proposals advance in multiple languages','Language committees advance proposals that bring richer pattern matching to everyday code.'),
('languages','Formatter wars end with opinionated defaults','Teams standardize on zero-config formatters, reducing review noise.'),
('languages','Async runtimes get structured concurrency primitives','Structured concurrency helpers make cancellation and error propagation easier to reason about.'),
('languages','Language servers cut indexing time on large repos','Updated language servers use incremental indexing to stay responsive in monorepos.'),
('languages','Deprecation of legacy string APIs begins','Standard libraries start warning on ambiguous string and encoding functions.'),
('languages','Reproducible builds become a baseline expectation','Toolchains add flags and docs to make bit-for-bit reproducible builds routine.'),
('languages','Compiler diagnostics get friendlier','New releases rewrite error messages with concrete fix suggestions.'),
('languages','WebAssembly targets mature across toolchains','More languages ship stable WebAssembly output with smaller binaries.'),
('languages','Benchmarks show gains from profile-guided optimization','PGO moves from experimental to recommended in release builds.'),
('languages','Standard library adds first-class JSON streaming','A common pattern gets official support, removing a popular third-party dependency.'),
('languages','Type inference improves for generic-heavy code','Compilers infer more type arguments, trimming boilerplate in generic APIs.'),
('languages','Community survey highlights tooling as top priority','Developers rank build speed and debugging above new syntax features.'),
('languages/go','Go range-over-func iterators see wide adoption','Libraries adopt iterator functions, simplifying custom collection traversal.'),
('languages/go','Go toolchain directive makes version pinning explicit','The toolchain line in go.mod gives teams predictable builds across machines.'),
('languages/go','Go gets faster map implementation','A new hash map design improves lookup and insert performance on large maps.'),
('languages/go','Go vulnerability scanning lands in CI templates','govulncheck becomes a default step in many project templates.'),
('languages/go','Go slog becomes the logging default','Structured logging via slog replaces ad hoc loggers in new services.'),
('languages/go','Go generics tutorials cover constraints in depth','New docs explain type sets, constraints, and when not to use generics.'),
('languages/go','Go test caching improvements speed up CI','Smarter cache keys reduce repeated test runs in large modules.'),
('languages/go','Go 1.x security patch fixes net/http edge case','A patch release addresses a header-parsing issue affecting proxies.'),
('languages/go','Go modules proxy adds checksum transparency docs','Documentation clarifies how checksum database lookups protect builds.'),
('languages/go','Go fuzzing graduates into everyday workflows','Fuzz tests are now commonly committed alongside unit tests.'),
('languages/go','Go PGO reduces CPU usage in production services','Teams report single-digit percentage wins after enabling profile-guided builds.'),
('languages/go','Go embed patterns for shipping static assets','Best practices emerge for embedding templates and migrations in binaries.'),
('languages/go','Go workspace mode simplifies multi-module repos','go.work files reduce replace-directive clutter in monorepos.'),
('languages/go','Go error handling proposals focus on ergonomics','Discussions center on reducing boilerplate without hiding control flow.'),
('languages/go','Go profiling tools gain flame graph views','The built-in pprof UI improves navigation for large profiles.'),
('languages/python','Python free-threaded builds reach broader testing','Experimental no-GIL builds attract compatibility reports from major libraries.'),
('languages/python','Python type checker speeds improve dramatically','Newer checkers analyze large codebases in seconds rather than minutes.'),
('languages/python','Python packaging adopts a unified lockfile format','A standard lockfile format aims to unify tooling across installers.'),
('languages/python','Python 3.x adds clearer error locations','Tracebacks now highlight the exact failing expression.'),
('languages/python','Python JIT compiler shows early gains','The experimental JIT delivers modest speedups on numeric loops.'),
('languages/python','Python dataclasses gain new ergonomics','Small additions reduce the need for third-party model libraries.'),
('languages/python','Python asyncio task groups become the norm','TaskGroup replaces gather in most new async code examples.'),
('languages/python','Python virtual environments simplified by new tooling','Fast resolvers make environment setup nearly instant for most projects.'),
('languages/python','Python security release patches tarfile extraction','A fix hardens archive extraction against path traversal.'),
('languages/python','Python standard library removes long-deprecated modules','Dead batteries are removed, prompting migration guides.'),
('languages/python','Python data tooling embraces columnar formats','DataFrame libraries add native support for Arrow-backed types.'),
('languages/python','Python docs overhaul improves search','The documentation site gets faster search and clearer navigation.'),
('languages/python','Python testing: pytest plugins to watch','New plugins add snapshot testing and better parallelism.'),
('languages/python','Python 2-to-3 holdouts finally migrate','Long-lived internal tools complete their migration, citing tooling help.'),
('languages/python','Python CLI frameworks compared','A look at argparse, Click, and Typer for modern command-line apps.'),
('languages/javascript','TypeScript native compiler preview speeds up builds','A native port promises several-fold faster type checking in large projects.'),
('languages/javascript','ECMAScript proposal for pipeline operator advances','The proposal moves forward with a revised syntax.'),
('languages/javascript','TypeScript adds stricter inference for narrowing','Control-flow analysis catches more bugs without new annotations.'),
('languages/javascript','Temporal API nears stable browser support','Date handling finally gets a sane, immutable standard API.'),
('languages/javascript','npm provenance badges spread across popular packages','Maintainers publish with attestations that link builds to source.'),
('languages/javascript','Iterator helpers land in major engines','map, filter, and take become available on iterators natively.'),
('languages/javascript','TypeScript enums fall out of favor','Style guides recommend const objects and unions instead.'),
('languages/javascript','Bundler benchmarks shift as Rust tools mature','Rust-based bundlers cut CI build times for large apps.'),
('languages/javascript','JavaScript decorators reach stage four','Standard decorators enable clean metadata and class augmentation.'),
('languages/javascript','Package exports maps cause migration headaches','Libraries fix dual ESM/CJS publishing problems with clearer guides.'),
('languages/javascript','Source maps get standardized debugging IDs','Debug IDs make symbolication reliable across deploys.'),
('languages/javascript','TypeScript project references simplify monorepos','Incremental builds cut rebuild time in multi-package repos.'),
('languages/javascript','Runtime permissions model gains traction','Sandboxed script execution is now an option in more runtimes.'),
('languages/javascript','Regex improvements: named groups and set notation','New regex features make complex matching more readable.'),
('languages/javascript','State of JS survey: tooling fatigue easing','Respondents report fewer build-tool migrations this year.'),
('languages/rust','Rust async closures stabilize','Async closures simplify callback-heavy code without boxing.'),
('languages/rust','Rust 2024 edition migration guide published','The guide walks through automatic fixes and manual changes.'),
('languages/rust','Cargo adds faster dependency resolution','Resolver improvements speed up large workspaces.'),
('languages/rust','Rust in the Linux kernel expands to new drivers','More subsystems accept Rust drivers with safe abstractions.'),
('languages/rust','Rust compile times drop with new linker defaults','A faster default linker trims incremental build time.'),
('languages/rust','Rust error handling libraries compared','thiserror, anyhow, and snafu: when to use each.'),
('languages/rust','Rust let-chains stabilize','let-chains remove nested if-let pyramids.'),
('languages/rust','Rust security advisory database adds tooling','cargo-audit output gets richer fix guidance.'),
('languages/rust','Rust embedded ecosystem hits a milestone','HAL crates standardize on shared async traits.'),
('languages/rust','Rust trait objects get upcasting','Trait upcasting lands, simplifying object hierarchies.'),
('languages/rust','Rust GUI toolkits mature','Several toolkits reach stable releases with accessibility support.'),
('languages/rust','Rust Cargo scripts make single-file tools easy','Single-file scripts can declare dependencies inline.'),
('languages/rust','Rust MSRV policies for popular crates','Maintainers document minimum supported versions more clearly.'),
('languages/rust','Rust WebAssembly component tooling improves','Component model tooling reduces glue code.'),
('languages/rust','Rust unsafe guidelines get a rewrite','New docs explain soundness rules with practical examples.'),
('languages/kotlin','Kotlin K2 compiler becomes the default','K2 brings faster compilation and improved smart casts.'),
('languages/kotlin','Kotlin context parameters enter preview','Context parameters replace context receivers with clearer scoping.'),
('languages/kotlin','Kotlin coroutines debugging gets better tooling','IDE support makes coroutine stack traces readable.'),
('languages/kotlin','Kotlin Multiplatform adoption survey results','More teams share business logic across Android and iOS.'),
('languages/kotlin','Kotlin serialization adds new formats','Support for additional binary formats improves interop.'),
('languages/kotlin','Kotlin Gradle plugin reduces configuration time','Build performance improvements help large multi-module projects.'),
('languages/kotlin','Kotlin value classes: practical patterns','Where inline value classes shine and where they do not.'),
('languages/kotlin','Kotlin Flow operators explained','A tour of buffering, conflation, and backpressure.'),
('languages/kotlin','Kotlin wasm target reaches beta','Compose for Web examples demonstrate the new target.'),
('languages/kotlin','Kotlin null-safety pitfalls with Java interop','Platform types still bite; here is how teams guard against them.'),
('languages/kotlin','Kotlin DSL best practices for Gradle builds','Typed accessors and convention plugins keep builds tidy.'),
('languages/kotlin','Kotlin Notebook improves data exploration','Notebook features target data science workflows.'),
('languages/kotlin','Kotlin Ktor 3 adds server improvements','Ktor updates focus on performance and simpler routing.'),
('languages/kotlin','Kotlin Power-assert plugin helps tests','Power-assert produces diagrams for failed assertions.'),
('languages/kotlin','Kotlin style guide updates for 2026','Updated conventions on naming and file structure.'),
('languages/swift','Swift 6 strict concurrency becomes easier to adopt','Migration tooling reduces the pain of data-race diagnostics.'),
('languages/swift','Swift Testing replaces XCTest for new projects','Macros-based tests reduce boilerplate.'),
('languages/swift','Swift on the server gains Linux tooling','Improved Linux static SDKs simplify deployments.'),
('languages/swift','Swift macros ecosystem grows','Popular libraries ship macros to cut repetitive code.'),
('languages/swift','Swift embedded mode targets microcontrollers','A reduced runtime enables Swift on tiny devices.'),
('languages/swift','SwiftData tips for migrations','Schema versioning patterns that avoid data loss.'),
('languages/swift','Swift package plugins automate codegen','Build tool plugins reduce manual scripts.'),
('languages/swift','Swift typed throws arrive','Typed throws improve error handling clarity.'),
('languages/swift','Swift Observation framework simplifies state','Observation reduces boilerplate in SwiftUI models.'),
('languages/swift','Swift compiler performance on large projects','Build-time diagnostics reveal slow expressions.'),
('languages/swift','Swift ownership features explained','Noncopyable types and borrowing in practice.'),
('languages/swift','Swift regex literals in the wild','Real-world patterns using the typed regex builder.'),
('languages/swift','Swift Package Index adds compatibility matrix','Maintainers get platform and version support at a glance.'),
('languages/swift','Swift concurrency actors: common mistakes','Avoid reentrancy bugs with these guidelines.'),
('languages/swift','Swift for Android toolchain preview','Early tooling explores sharing Swift code on Android.'),
('languages/java','Java virtual threads see production use','Teams report simpler concurrency and higher throughput with virtual threads.'),
('languages/java','Java records and sealed types reshape domain models','Pattern matching with sealed hierarchies replaces visitor boilerplate.'),
('languages/java','Java startup time improves with ahead-of-time cache','AOT caching shortens warmup for containerized apps.'),
('languages/java','Java security update fixes TLS handling issue','The quarterly update patches several moderate issues.'),
('languages/java','Java structured concurrency previews again','The API refines scope handling for subtasks.'),
('languages/java','Java Foreign Function API replaces JNI use cases','Native interop gets safer and simpler.'),
('languages/java','Java garbage collector tuning in 2026','Generational ZGC becomes a solid default for latency-sensitive services.'),
('languages/java','Java build tools compared','Maven and Gradle trade-offs for new projects.'),
('languages/java','Java string templates revisited','The feature returns with a redesigned approach.'),
('languages/java','Java module system adoption still slow','Few apps use modules, but libraries are catching up.'),
('languages/java','Java Spring Boot migration guide','Upgrading across major versions with minimal breakage.'),
('languages/java','Java unnamed classes lower the beginner barrier','Simplified entry points make teaching easier.'),
('languages/java','Java vector API incubates further','SIMD support continues to mature.'),
('languages/java','Java observability with OpenTelemetry','Auto-instrumentation reduces manual tracing work.'),
('languages/java','Java LTS roadmap and support timelines','Vendors publish extended support windows.'),
('web','Core Web Vitals thresholds updated','Interaction to Next Paint remains the key responsiveness metric for 2026.'),
('web','View Transitions land across browsers','Cross-document transitions make multi-page apps feel native.'),
('web','CSS container queries become everyday tools','Component-level responsive design is now broadly supported.'),
('web','Web accessibility law deadlines approach','Teams scramble to audit sites against updated standards.'),
('web','HTTP/3 adoption passes a major milestone','Most CDN traffic now negotiates HTTP/3 where available.'),
('web','Islands architecture goes mainstream','Partial hydration reduces JavaScript shipped to clients.'),
('web','Passkeys replace passwords on major sites','Sign-in flows simplify as passkey support spreads.'),
('web','CSS nesting and :has() unlock new patterns','Parent selectors and native nesting reduce preprocessor need.'),
('web','Image formats: AVIF and JPEG XL debate continues','Browsers weigh support as tooling improves.'),
('web','Service workers: caching strategies revisited','Practical patterns for offline-first apps.'),
('web','Web components get declarative shadow DOM','Server-rendered components work without client JavaScript.'),
('web','Edge rendering trade-offs explained','When rendering near users helps and when it does not.'),
('web','Content Security Policy rollout guide','Incremental CSP adoption without breaking pages.'),
('web','Core web tooling: Lighthouse updates','New audits focus on real-user performance data.'),
('web','Third-party scripts under scrutiny','Browsers add controls to limit the cost of embeds.'),
('web/react','React compiler reaches stable release','Automatic memoization reduces manual useMemo and useCallback.'),
('web/react','React Server Components patterns settle','Teams converge on data fetching and caching conventions.'),
('web/react','React 19 actions simplify forms','Form actions and optimistic updates cut boilerplate.'),
('web/react','React DevTools gets profiler improvements','New views make render causes easier to trace.'),
('web/react','React testing library best practices','Query by role and avoid implementation details.'),
('web/react','React state libraries compared','Context, Zustand, Jotai, and Redux Toolkit trade-offs.'),
('web/react','React Suspense for data fetching explained','Patterns for loading states and error boundaries.'),
('web/react','React security advisory affects server rendering','Upgrade guidance for a serialization issue.'),
('web/react','React routing options in 2026','Compare framework routers and standalone libraries.'),
('web/react','React performance: avoiding unnecessary renders','Profiling workflow for slow component trees.'),
('web/react','React concurrent features in practice','Transitions and deferred values for responsive UI.'),
('web/react','React accessibility checklist','Focus management and ARIA pitfalls to avoid.'),
('web/react','React Native web interop improves','Shared components across web and mobile get easier.'),
('web/react','React ecosystem: new UI kits','Headless component libraries gain popularity.'),
('web/react','React migration: class components to hooks','A staged approach for legacy codebases.'),
('web/nextjs','Next.js caching defaults change','Fetch requests are no longer cached by default.'),
('web/nextjs','Next.js partial prerendering stabilizes','Static shells with streamed dynamic content.'),
('web/nextjs','Next.js Turbopack becomes the default bundler','Dev server startup and HMR get noticeably faster.'),
('web/nextjs','Next.js middleware moves to the Node runtime','More libraries work in middleware.'),
('web/nextjs','Next.js image optimization pricing changes','Self-hosting guidance for cost control.'),
('web/nextjs','Next.js app router migration lessons','Real teams share pitfalls from pages router migrations.'),
('web/nextjs','Next.js server actions security tips','Validate input and authorize every action.'),
('web/nextjs','Next.js self-hosting guide updated','Docker and standalone output recommendations.'),
('web/nextjs','Next.js ISR on-demand revalidation patterns','Tag-based revalidation for content sites.'),
('web/nextjs','Next.js security patch for authorization bypass','Upgrade promptly if using certain middleware patterns.'),
('web/nextjs','Next.js internationalization routing','Locale-based routing best practices.'),
('web/nextjs','Next.js bundle size analysis','Find heavy dependencies with the built-in analyzer.'),
('web/nextjs','Next.js with edge databases','Connection pooling considerations at the edge.'),
('web/nextjs','Next.js testing strategies','Component, integration, and end-to-end layers.'),
('web/nextjs','Next.js templates for SaaS starters','Common stacks for quick product launches.'),
('web/angular','Angular signals become the default reactivity model','Zoneless change detection matures with signals.'),
('web/angular','Angular standalone components are the norm','NgModules fade from new project templates.'),
('web/angular','Angular new control flow syntax','@if and @for replace structural directives.'),
('web/angular','Angular SSR hydration improves','Incremental hydration reduces initial JavaScript.'),
('web/angular','Angular CLI build times drop with esbuild','The application builder makes builds noticeably faster.'),
('web/angular','Angular migration to zoneless apps','Steps to remove zone.js safely.'),
('web/angular','Angular Material gets a design refresh','New tokens simplify theming.'),
('web/angular','Angular testing: moving beyond Karma','Alternatives for faster unit tests.'),
('web/angular','Angular forms: typed reactive forms','Strong typing prevents common mistakes.'),
('web/angular','Angular security advisory for template injection','Patch guidance for affected versions.'),
('web/angular','Angular deferrable views explained','Lazy load parts of templates declaratively.'),
('web/angular','Angular monorepo tooling comparison','Nx and Angular workspaces compared.'),
('web/angular','Angular state management with signals store','Lightweight stores gain traction.'),
('web/angular','Angular i18n improvements','Build-time translation workflow updates.'),
('web/angular','Angular roadmap highlights','What the team is prioritizing next.'),
('web/vue','Vue vapor mode enters beta','Compiler-driven rendering skips the virtual DOM.'),
('web/vue','Vue 3 reactivity internals deep dive','How refs and effects track dependencies.'),
('web/vue','Vue Router adds typed routes','Type-safe navigation reduces runtime errors.'),
('web/vue','Pinia becomes the recommended store','Migration notes from Vuex.'),
('web/vue','Vue SSR with Nuxt improvements','Faster server rendering and better caching.'),
('web/vue','Vue testing with Vitest','Component testing setup that is quick and reliable.'),
('web/vue','Vue composition API patterns','Composables for shared logic done right.'),
('web/vue','Vue devtools update','Timeline and inspector improvements.'),
('web/vue','Vue performance tips','Avoid deep reactivity on large datasets.'),
('web/vue','Vue ecosystem UI libraries','Headless and styled component sets compared.'),
('web/vue','Vue security notes on v-html','Sanitize content before rendering HTML.'),
('web/vue','Vue 2 end-of-life migration guide','Plan upgrades now to stay supported.'),
('web/vue','Vue and TypeScript best practices','Typing props, emits, and slots.'),
('web/vue','Vue accessibility patterns','Focus traps, announcements, and keyboard support.'),
('web/vue','Vue community survey','Developers report growing satisfaction with tooling.'),
('web/nodejs','Node.js adds built-in TypeScript type stripping','Run TypeScript files directly without a separate build step.'),
('web/nodejs','Node.js permission model matures','Restrict file and network access for scripts.'),
('web/nodejs','Node.js test runner gains coverage','The built-in runner covers many project needs.'),
('web/nodejs','Node.js security release patches HTTP parsing','Update to the latest patch of your LTS line.'),
('web/nodejs','Node.js fetch and streams improvements','Web-standard APIs reduce dependencies.'),
('web/nodejs','Node.js startup snapshots speed CLIs','Snapshots cut load time for large tools.'),
('web/nodejs','Node.js ESM and CJS interop eases','require(esm) removes a long-standing pain point.'),
('web/nodejs','Node.js LTS schedule announced','Plan upgrades around the new release calendar.'),
('web/nodejs','Node.js worker threads patterns','Offload CPU work without blocking the event loop.'),
('web/nodejs','Node.js diagnostics and profiling guide','Find memory leaks with heap snapshots.'),
('web/nodejs','Node.js single executable applications','Ship tools as one binary.'),
('web/nodejs','Node.js env file support','Native .env loading reduces extra packages.'),
('web/nodejs','Node.js frameworks compared','Fastify, Express 5, and Hono in practice.'),
('web/nodejs','Node.js observability tips','Tracing HTTP and database calls end to end.'),
('web/nodejs','Node.js release notes digest','Highlights from the latest current release.'),
('web/browsers','Chrome ships new anchor positioning','Position tooltips and popovers in pure CSS.'),
('web/browsers','Firefox improves privacy protections','New defaults reduce cross-site tracking.'),
('web/browsers','Safari adds new web platform features','Updates close long-standing compatibility gaps.'),
('web/browsers','Browser interop 2026 goals announced','Vendors align on a shared list of focus areas.'),
('web/browsers','Chrome deprecates third-party cookies path','Privacy-preserving alternatives continue to roll out.'),
('web/browsers','Browsers speed up JavaScript startup','Engines cut parse and compile costs.'),
('web/browsers','WebGPU reaches all major browsers','GPU compute and rendering arrive for the web.'),
('web/browsers','Popover API simplifies overlays','Native popovers reduce custom JavaScript.'),
('web/browsers','Browser extension manifest changes','What developers must update for compatibility.'),
('web/browsers','Browser devtools tips','Underused panels that save debugging time.'),
('web/browsers','Web Push expands on mobile browsers','Notifications reach more users on installed web apps.'),
('web/browsers','Browser security: site isolation updates','Stronger process isolation lowers exploit risk.'),
('web/browsers','Scroll-driven animations explained','Animate on scroll without JavaScript.'),
('web/browsers','Browser storage limits and eviction','How quotas work across engines.'),
('web/browsers','Browser release calendar','Upcoming stable releases and what to expect.'),
('mobile','Mobile app store policies tighten','New review guidelines affect subscriptions and permissions.'),
('mobile','On-device AI features arrive in mobile SDKs','Platform APIs expose local models for text and vision.'),
('mobile','Passkeys on mobile: implementation guide','Sign in smoothly across Android and iOS.'),
('mobile','Mobile app size reduction techniques','Trim binaries with modern bundling and asset strategies.'),
('mobile','Mobile accessibility testing checklist','Cover screen readers, contrast, and touch targets.'),
('mobile','Battery impact of background work','Scheduling guidance from both platforms.'),
('mobile','Mobile CI/CD pipelines compared','Fast build and distribution options.'),
('mobile','Mobile analytics privacy changes','What data you can still collect.'),
('mobile','Foldables and large screens drive layout changes','Adaptive layouts become table stakes.'),
('mobile','Mobile app startup performance','Measure and cut cold-start time.'),
('mobile','Offline-first sync patterns','Conflict resolution strategies for mobile data.'),
('mobile','Mobile security baseline','Certificate pinning and secure storage reminders.'),
('mobile','Push notification best practices','Respect user attention and platform limits.'),
('mobile','Mobile developer survey results','Cross-platform share continues to grow.'),
('mobile','Deep linking and app links explained','Handle universal links without surprises.'),
('mobile/android','Android 16 behavior changes for developers','Review edge-to-edge and background restrictions.'),
('mobile/android','Jetpack Compose performance improvements','Strong skipping mode reduces recompositions.'),
('mobile/android','Android Studio adds AI-assisted debugging','New tools help trace crashes to code.'),
('mobile/android','Android predictive back gesture becomes mandatory','Update navigation to support the new animation.'),
('mobile/android','Android photo picker replaces storage permissions','Reduce permissions with the system picker.'),
('mobile/android','Android Gradle plugin 9 migration','Breaking changes and fixes to expect.'),
('mobile/android','Android adaptive layouts guide','Window size classes in practice.'),
('mobile/android','Android Play Console policy updates','Target API requirements and deadlines.'),
('mobile/android','Android Baseline Profiles cut startup','Generate profiles to speed up cold starts.'),
('mobile/android','Android Credential Manager rollout','Unified sign-in with passkeys and passwords.'),
('mobile/android','Android security bulletin summary','Monthly patch highlights.'),
('mobile/android','Android WorkManager best practices','Reliable background tasks without battery drain.'),
('mobile/android','Android Room database migrations','Schema changes without data loss.'),
('mobile/android','Android Material 3 expressive updates','New components and motion guidance.'),
('mobile/android','Android testing pyramid for Compose','Unit, UI, and screenshot tests.'),
('mobile/ios','iOS new SDK requirements for App Store','Apps must build with the latest Xcode soon.'),
('mobile/ios','SwiftUI navigation APIs improve','Stack and split view handling gets simpler.'),
('mobile/ios','iOS privacy manifests enforcement','Declare required reason APIs to avoid rejection.'),
('mobile/ios','Xcode build performance tips','Explicit modules and caching cut build times.'),
('mobile/ios','iOS Live Activities best practices','Design glanceable updates within system limits.'),
('mobile/ios','iOS widgets and App Intents','Surface app features across the system.'),
('mobile/ios','iOS accessibility: Dynamic Type pitfalls','Layouts that survive large text sizes.'),
('mobile/ios','iOS background tasks guidance','BGTaskScheduler dos and donts.'),
('mobile/ios','iOS in-app purchase StoreKit updates','Simpler subscription handling with StoreKit 2.'),
('mobile/ios','iOS TestFlight tips for faster review','Prepare builds to speed up beta distribution.'),
('mobile/ios','iOS security: keychain best practices','Store secrets correctly with proper access control.'),
('mobile/ios','iOS memory debugging workflow','Use Instruments to find leaks and spikes.'),
('mobile/ios','iOS app clips guide','Lightweight experiences for quick tasks.'),
('mobile/ios','iOS UIKit to SwiftUI migration','Incremental adoption patterns.'),
('mobile/ios','iOS release notes digest','Developer-facing changes in the latest update.'),
('mobile/flutter','Flutter Impeller engine is default everywhere','Smoother animations with fewer shader jank issues.'),
('mobile/flutter','Flutter web WebAssembly support improves','Wasm builds get faster loads.'),
('mobile/flutter','Flutter state management in 2026','Riverpod, Bloc, and Provider compared.'),
('mobile/flutter','Flutter DevTools adds new memory views','Track allocations more easily.'),
('mobile/flutter','Flutter packages to audit','Check pub.dev scores and maintenance signals.'),
('mobile/flutter','Flutter platform views performance','Embed native views with fewer trade-offs.'),
('mobile/flutter','Flutter testing strategies','Widget, golden, and integration tests.'),
('mobile/flutter','Flutter and Dart macros update','Metaprogramming plans and status.'),
('mobile/flutter','Flutter app size optimization','Tree shaking and deferred components.'),
('mobile/flutter','Flutter accessibility guidance','Semantics widgets in complex screens.'),
('mobile/flutter','Flutter desktop apps in production','Case studies from teams shipping to desktop.'),
('mobile/flutter','Flutter CI with fastlane','Automate signing and uploads.'),
('mobile/flutter','Flutter animation recipes','Explicit and implicit animations explained.'),
('mobile/flutter','Flutter plugin development tips','Write federated plugins with fewer pitfalls.'),
('mobile/flutter','Flutter release notes digest','Highlights from the latest stable channel.'),
('mobile/react-native','React Native new architecture becomes default','Fabric and TurboModules reach broad library support.'),
('mobile/react-native','React Native Hermes engine improvements','Faster startup and lower memory usage.'),
('mobile/react-native','React Native Expo SDK update','New SDK brings updated native modules.'),
('mobile/react-native','React Native navigation libraries compared','React Navigation and Expo Router trade-offs.'),
('mobile/react-native','React Native performance profiling','Find JS thread stalls and slow renders.'),
('mobile/react-native','React Native upgrade helper tips','Smooth upgrades across versions.'),
('mobile/react-native','React Native web code sharing','Share components with react-native-web.'),
('mobile/react-native','React Native animations with Reanimated','Worklets keep animations on the UI thread.'),
('mobile/react-native','React Native testing setup','Jest and Detox for reliable coverage.'),
('mobile/react-native','React Native security hardening','Secure storage and jailbreak detection basics.'),
('mobile/react-native','React Native native modules guide','Write modules for the new architecture.'),
('mobile/react-native','React Native OTA updates explained','Ship JS fixes safely with staged rollouts.'),
('mobile/react-native','React Native layout gotchas','Flexbox differences that surprise web developers.'),
('mobile/react-native','React Native monorepo setup','Share code with workspaces and Metro config.'),
('mobile/react-native','React Native release notes digest','Changes worth knowing in the latest version.'),
('mobile/kmp','Compose Multiplatform for iOS reaches stable','Share UI across Android and iOS with a single codebase.'),
('mobile/kmp','Kotlin Multiplatform library ecosystem grows','More libraries publish multiplatform artifacts.'),
('mobile/kmp','KMP project structure recommendations','Organize shared modules and platform code.'),
('mobile/kmp','KMP networking with Ktor','Shared API clients across platforms.'),
('mobile/kmp','KMP persistence options','SQLDelight and Room multiplatform compared.'),
('mobile/kmp','KMP dependency injection with Koin','Share DI setup and platform bindings.'),
('mobile/kmp','KMP testing across platforms','Run shared tests on JVM and native targets.'),
('mobile/kmp','KMP and SwiftUI interop','Expose Kotlin APIs idiomatically to Swift.'),
('mobile/kmp','KMP build performance tips','Cache and configure Gradle for faster builds.'),
('mobile/kmp','KMP in production: team stories','Lessons from companies sharing business logic.'),
('mobile/kmp','Compose Multiplatform desktop update','Window management and rendering improvements.'),
('mobile/kmp','KMP resources and localization','Shared strings and images made simple.'),
('mobile/kmp','KMP CI setup with GitHub Actions','Build and test Android and iOS targets.'),
('mobile/kmp','KMP navigation libraries compared','Decompose, Voyager, and Navigation Compose.'),
('mobile/kmp','KMP roadmap highlights','Upcoming focus areas for the platform.'),
('cloud','Cloud cost optimization moves into engineering workflows','FinOps checks now run in pull requests, not just in finance reviews.'),
('cloud','Multi-region failover patterns revisited','Lessons from recent outages shape resilience guidance.'),
('cloud','Serverless containers blur the line with functions','Scale-to-zero container platforms gain features.'),
('cloud','Platform engineering teams adopt golden paths','Internal developer platforms reduce setup time.'),
('cloud','Cloud carbon reporting gets standardized','Providers expose emissions data in billing exports.'),
('cloud','Zero trust networking in practice','Identity-aware proxies replace VPN-first designs.'),
('cloud','Cloud egress fee changes reshape architectures','Providers waive fees for migrations and some transfers.'),
('cloud','Observability costs under review','Teams cut telemetry volume without losing signal.'),
('cloud','Infrastructure drift detection tools compared','Catch manual changes before they cause incidents.'),
('cloud','Edge compute platforms expand','More regions and runtimes for latency-sensitive workloads.'),
('cloud','Cloud IAM least privilege guide','Tools suggest narrower roles from audit logs.'),
('cloud','Disaster recovery testing checklist','Practice restores, not just backups.'),
('cloud','Confidential computing reaches mainstream','Encrypted-in-use VMs become a checkbox option.'),
('cloud','Cloud-native security posture trends','Misconfigurations remain the top risk.'),
('cloud','Cloud certification and skills report','Demand grows for platform and security skills.'),
('cloud/aws','AWS Lambda adds new runtime and scaling controls','Faster scaling and runtime updates help bursty workloads.'),
('cloud/aws','AWS S3 gains new data protection features','Additional safeguards reduce accidental deletion risk.'),
('cloud/aws','AWS IAM Identity Center updates','Simpler permission sets for multi-account setups.'),
('cloud/aws','AWS Graviton instances show cost savings','Arm instances cut compute bills for common workloads.'),
('cloud/aws','AWS CDK improvements','New constructs reduce boilerplate in infrastructure code.'),
('cloud/aws','AWS RDS and Aurora feature roundup','Serverless scaling and upgrade tooling improve.'),
('cloud/aws','AWS EKS upgrade strategies','Blue/green node group upgrades with less risk.'),
('cloud/aws','AWS networking: VPC Lattice explained','Service-to-service networking with policy.'),
('cloud/aws','AWS cost explorer new views','Break down spend by tag and usage type.'),
('cloud/aws','AWS security hub updates','Consolidated findings and automation rules.'),
('cloud/aws','AWS CloudFront and edge function changes','Run lightweight logic at the CDN edge.'),
('cloud/aws','AWS Step Functions patterns','Orchestrate workflows with fewer moving parts.'),
('cloud/aws','AWS regional expansion announced','New regions and local zones launch.'),
('cloud/aws','AWS Bedrock model catalog grows','More foundation models become available.'),
('cloud/aws','AWS re:Invent recap for developers','Developer-facing launches worth reviewing.'),
('cloud/gcp','Google Cloud Run adds new scaling features','Better concurrency controls and faster cold starts.'),
('cloud/gcp','Google Cloud BigQuery gains new AI functions','SQL-native model calls simplify analytics pipelines.'),
('cloud/gcp','Google Cloud GKE Autopilot updates','More workloads supported without node management.'),
('cloud/gcp','Google Cloud IAM recommender improvements','Tighter role suggestions based on usage.'),
('cloud/gcp','Google Cloud Spanner price and feature changes','Lower entry cost for smaller deployments.'),
('cloud/gcp','Google Cloud Firestore enhancements','New query capabilities and indexing tools.'),
('cloud/gcp','Google Cloud Pub/Sub exactly-once tips','Design idempotent consumers regardless.'),
('cloud/gcp','Google Cloud Functions gen2 migration','Move from gen1 with minimal changes.'),
('cloud/gcp','Google Cloud logging cost control','Exclusion filters and log buckets explained.'),
('cloud/gcp','Google Cloud Armor and WAF updates','Stronger defaults for web apps.'),
('cloud/gcp','Google Cloud Artifact Registry features','Remote repos and vulnerability scanning.'),
('cloud/gcp','Google Cloud Vertex AI platform news','New tooling for evaluation and deployment.'),
('cloud/gcp','Google Cloud networking: Private Service Connect','Private endpoints for managed services.'),
('cloud/gcp','Google Cloud Terraform provider updates','New resources and deprecations.'),
('cloud/gcp','Google Cloud Next recap for developers','Key announcements for builders.'),
('cloud/azure','Azure Functions flex consumption GA','Faster scaling and networking options for serverless.'),
('cloud/azure','Azure AKS automatic mode simplifies clusters','Opinionated defaults reduce operational burden.'),
('cloud/azure','Azure Entra ID security defaults','Conditional access guidance for small teams.'),
('cloud/azure','Azure Cosmos DB new capabilities','Vector search and throughput controls.'),
('cloud/azure','Azure DevOps and GitHub integration','Unified pipelines and boards.'),
('cloud/azure','Azure Bicep adoption tips','Modules and linting for cleaner templates.'),
('cloud/azure','Azure SQL updates','Hyperscale and serverless improvements.'),
('cloud/azure','Azure cost management tips','Budgets and anomaly alerts.'),
('cloud/azure','Azure networking: Front Door changes','Routing and WAF rules get new options.'),
('cloud/azure','Azure OpenAI service updates','New models and regional availability.'),
('cloud/azure','Azure Container Apps feature roundup','Jobs, Dapr, and scaling rules.'),
('cloud/azure','Azure Monitor and OpenTelemetry','Native OTel ingestion simplifies tracing.'),
('cloud/azure','Azure security center recommendations','Prioritize fixes by exploitability.'),
('cloud/azure','Azure landing zone guidance','Reference architecture updates.'),
('cloud/azure','Azure region and availability zone news','New zones improve resilience options.'),
('cloud/kubernetes','Kubernetes sidecar containers go stable','Native sidecars fix startup and shutdown ordering.'),
('cloud/kubernetes','Kubernetes Gateway API replaces Ingress for new setups','Role-oriented routing becomes the recommended path.'),
('cloud/kubernetes','Kubernetes release adds in-place pod resize','Resize resources without restarts.'),
('cloud/kubernetes','Kubernetes security patch for node components','Upgrade guidance for supported versions.'),
('cloud/kubernetes','Kubernetes autoscaling: KEDA and HPA together','Event-driven scaling patterns.'),
('cloud/kubernetes','Kubernetes cost visibility tools','Allocate spend per namespace and team.'),
('cloud/kubernetes','Kubernetes network policy best practices','Default deny with explicit allows.'),
('cloud/kubernetes','Kubernetes Helm vs Kustomize','Choosing a packaging approach.'),
('cloud/kubernetes','Kubernetes upgrades without downtime','PodDisruptionBudgets and surge strategies.'),
('cloud/kubernetes','Kubernetes observability stack options','Prometheus, OpenTelemetry, and logs.'),
('cloud/kubernetes','Kubernetes operators pitfalls','Reconcile loops and idempotency tips.'),
('cloud/kubernetes','Kubernetes secrets management','External secrets and encryption at rest.'),
('cloud/kubernetes','Kubernetes API deprecations to watch','Migrate manifests before removal.'),
('cloud/kubernetes','Kubernetes multi-cluster strategies','Fleet management and GitOps.'),
('cloud/kubernetes','Kubernetes release calendar','Upcoming versions and end-of-life dates.'),
('cloud/docker','Docker Desktop adds new build caching','Cloud builders speed up CI image builds.'),
('cloud/docker','Docker Compose watch improves dev loops','Sync and rebuild on change automatically.'),
('cloud/docker','Docker image scanning gets deeper','SBOM generation and policy checks built in.'),
('cloud/docker','Docker multi-stage build patterns','Smaller images with cleaner Dockerfiles.'),
('cloud/docker','Docker rootless mode in production','Reduce blast radius for compromised containers.'),
('cloud/docker','Docker BuildKit features worth using','Secrets mounts and cache exports.'),
('cloud/docker','Docker base image choices compared','Distroless, Alpine, and slim variants.'),
('cloud/docker','Docker networking explained','Bridge, host, and overlay networks.'),
('cloud/docker','Docker volume backup strategies','Safe approaches for stateful dev databases.'),
('cloud/docker','Docker security advisory for container runtime','Update to a patched engine version.'),
('cloud/docker','Docker Hub rate limit changes','Mirror images to avoid CI failures.'),
('cloud/docker','Docker healthchecks best practices','Meaningful probes for orchestrators.'),
('cloud/docker','Docker on Apple Silicon tips','Run multi-arch images efficiently.'),
('cloud/docker','Docker Model Runner for local AI','Run models locally from container tooling.'),
('cloud/docker','Docker release notes digest','Highlights from the latest engine version.'),
('cloud/terraform','Terraform testing framework matures','Native tests validate modules without extra tools.'),
('cloud/terraform','OpenTofu and Terraform divergence widens','Teams weigh features and licensing.'),
('cloud/terraform','Terraform provider version pinning guide','Lock files and constraints that prevent surprises.'),
('cloud/terraform','Terraform state management tips','Remote backends, locking, and safe refactors.'),
('cloud/terraform','Terraform module design principles','Small, composable modules with clear inputs.'),
('cloud/terraform','Terraform import blocks simplify adoption','Bring existing resources under management declaratively.'),
('cloud/terraform','Terraform policy as code options','Sentinel, OPA, and Checkov compared.'),
('cloud/terraform','Terraform drift detection workflows','Schedule plans to spot manual changes.'),
('cloud/terraform','Terraform CI pipelines','Plan on pull request, apply on merge.'),
('cloud/terraform','Terraform secrets handling','Avoid secrets in state where possible.'),
('cloud/terraform','Terraform for_each pitfalls','Stable keys prevent resource replacement.'),
('cloud/terraform','Terraform workspaces vs directories','Choosing an environment strategy.'),
('cloud/terraform','Terraform cloud cost estimation','Predict spend in code review.'),
('cloud/terraform','Terraform refactoring with moved blocks','Rename resources without destroying them.'),
('cloud/terraform','Terraform release notes digest','Highlights from the latest version.'),
('databases','Database vector search becomes a standard feature','Relational and document stores add vector indexes.'),
('databases','Serverless databases drop entry prices','Branching and scale-to-zero change dev workflows.'),
('databases','Schema migration tools compared','Zero-downtime strategies for large tables.'),
('databases','Connection pooling explained','Why pools matter more with serverless.'),
('databases','Database backup and restore drills','Verify restores regularly.'),
('databases','Time-series databases in 2026','Specialized and general-purpose options.'),
('databases','Database indexing mistakes to avoid','Redundant and unused indexes cost writes.'),
('databases','Change data capture patterns','Stream changes to downstream systems reliably.'),
('databases','Database security checklist','Least privilege and encryption defaults.'),
('databases','Query performance observability','Find slow queries with built-in views.'),
('databases','Multi-tenant database designs','Schema per tenant vs shared tables.'),
('databases','Database benchmarking pitfalls','Realistic workloads beat synthetic numbers.'),
('databases','Embedded databases resurge','Local-first apps embrace in-process engines.'),
('databases','Database licensing changes','Open-source forks emerge after license shifts.'),
('databases','Data modeling for event-driven systems','Outbox pattern and idempotency.'),
('databases/postgres','PostgreSQL 17 improves vacuum and JSON','Faster maintenance and richer JSON_TABLE support.'),
('databases/postgres','PostgreSQL logical replication enhancements','Failover slots reduce manual intervention.'),
('databases/postgres','PostgreSQL pgvector performance gains','Faster indexes for similarity search.'),
('databases/postgres','PostgreSQL security release','Patch several vulnerabilities across supported branches.'),
('databases/postgres','PostgreSQL partitioning best practices','Prune partitions and manage retention.'),
('databases/postgres','PostgreSQL EXPLAIN reading guide','Understand costs, rows, and buffers.'),
('databases/postgres','PostgreSQL connection pooling with PgBouncer','Transaction pooling caveats.'),
('databases/postgres','PostgreSQL row-level security patterns','Multi-tenant isolation inside the database.'),
('databases/postgres','PostgreSQL extension ecosystem highlights','Useful extensions for production.'),
('databases/postgres','PostgreSQL upgrade paths with pg_upgrade','Plan major version upgrades safely.'),
('databases/postgres','PostgreSQL full-text search tuning','Weights, dictionaries, and GIN indexes.'),
('databases/postgres','PostgreSQL autovacuum tuning','Prevent bloat on busy tables.'),
('databases/postgres','PostgreSQL JSONB indexing strategies','Choose between GIN operators.'),
('databases/postgres','PostgreSQL high availability options','Patroni and managed alternatives.'),
('databases/postgres','PostgreSQL release roadmap','Features proposed for the next major version.'),
('databases/mysql','MySQL 9 innovation release highlights','New features arrive on the innovation track.'),
('databases/mysql','MySQL replication improvements','Group replication and failover tweaks.'),
('databases/mysql','MySQL index hints and optimizer changes','Review query plans after upgrading.'),
('databases/mysql','MySQL security advisory','Critical patch update summary.'),
('databases/mysql','MySQL vs MariaDB differences','Compatibility notes for migrations.'),
('databases/mysql','MySQL online schema change tools','gh-ost and pt-osc compared.'),
('databases/mysql','MySQL JSON functions guide','Query JSON columns effectively.'),
('databases/mysql','MySQL InnoDB tuning checklist','Buffer pool and log settings.'),
('databases/mysql','MySQL backup options','Logical and physical backup trade-offs.'),
('databases/mysql','MySQL character set pitfalls','Use utf8mb4 everywhere.'),
('databases/mysql','MySQL HeatWave analytics integration','Run analytics next to transactional data.'),
('databases/mysql','MySQL performance schema tips','Find hot queries with built-in tables.'),
('databases/mysql','MySQL connection limits and pooling','Avoid max connection errors.'),
('databases/mysql','MySQL cloud offerings compared','Managed MySQL across providers.'),
('databases/mysql','MySQL end-of-life dates','Plan migrations from older versions.'),
('databases/redis','Redis license change drives forks and new options','Valkey and others offer open alternatives.'),
('databases/redis','Redis 8 adds vector sets and new data types','Native vector support broadens use cases.'),
('databases/redis','Redis caching patterns revisited','Cache-aside, write-through, and stampede control.'),
('databases/redis','Redis persistence options explained','RDB and AOF trade-offs.'),
('databases/redis','Redis cluster resharding tips','Move slots with minimal disruption.'),
('databases/redis','Redis security hardening','ACLs, TLS, and network exposure.'),
('databases/redis','Redis streams for event processing','Consumer groups in practice.'),
('databases/redis','Redis memory optimization','Encoding and eviction policies.'),
('databases/redis','Redis rate limiting recipes','Token buckets and sliding windows.'),
('databases/redis','Redis client library updates','Connection handling and retries.'),
('databases/redis','Redis Lua scripting best practices','Atomic operations without long scripts.'),
('databases/redis','Redis pub/sub limits','When to use streams instead.'),
('databases/redis','Redis monitoring metrics','Key indicators to alert on.'),
('databases/redis','Redis managed services compared','Pricing and features across clouds.'),
('databases/redis','Redis release notes digest','Highlights from the latest stable version.'),
('databases/mongodb','MongoDB adds new search and vector features','Atlas Search and vector queries unify retrieval workflows.'),
('databases/mongodb','MongoDB schema design patterns','Embedding versus referencing decisions.'),
('databases/mongodb','MongoDB sharding key selection','Avoid hot shards with good keys.'),
('databases/mongodb','MongoDB aggregation pipeline tips','Optimize stages and use indexes.'),
('databases/mongodb','MongoDB security best practices','Auth, encryption, and network rules.'),
('databases/mongodb','MongoDB transactions in practice','When multi-document transactions are needed.'),
('databases/mongodb','MongoDB change streams guide','React to data changes in real time.'),
('databases/mongodb','MongoDB indexing strategies','Compound index order matters.'),
('databases/mongodb','MongoDB backup and restore','Point-in-time recovery options.'),
('databases/mongodb','MongoDB driver updates','New versions bring connection improvements.'),
('databases/mongodb','MongoDB Atlas pricing changes','Understand cluster tier adjustments.'),
('databases/mongodb','MongoDB time series collections','Efficient storage for metrics.'),
('databases/mongodb','MongoDB migration from relational','Plan data model changes first.'),
('databases/mongodb','MongoDB performance profiling','Use the profiler to find slow operations.'),
('databases/mongodb','MongoDB release notes digest','Highlights from the latest version.'),
('databases/sqlite','SQLite gains new JSON and concurrency features','Improvements make it viable for more server-side workloads.'),
('databases/sqlite','SQLite WAL mode best practices','Better concurrency with sensible settings.'),
('databases/sqlite','SQLite in production: lessons learned','Backups, replication, and limits.'),
('databases/sqlite','SQLite replication tools compared','Litestream and LiteFS approaches.'),
('databases/sqlite','SQLite full-text search with FTS5','Ranking and tokenizers explained.'),
('databases/sqlite','SQLite strict tables prevent type surprises','Enforce column types on new schemas.'),
('databases/sqlite','SQLite on mobile: tuning tips','Pragmas for faster writes.'),
('databases/sqlite','SQLite vector extensions','Run similarity search locally.'),
('databases/sqlite','SQLite WebAssembly in the browser','Persistent storage via OPFS.'),
('databases/sqlite','SQLite migration strategies','Schema changes with limited ALTER support.'),
('databases/sqlite','SQLite security update','Patch for a memory safety issue.'),
('databases/sqlite','SQLite testing with in-memory databases','Fast tests with caveats.'),
('databases/sqlite','SQLite performance pitfalls','Avoid autocommit and missing indexes.'),
('databases/sqlite','SQLite analytics with DuckDB comparison','When to choose each engine.'),
('databases/sqlite','SQLite release notes digest','Highlights from the latest release.'),
('ai','AI coding assistants shift toward agentic workflows','Tools now plan, edit, and test across files with human review gates.'),
('ai','Evaluation harnesses become a required engineering practice','Teams gate prompt and model changes behind regression suites.'),
('ai','Small language models win on-device use cases','Compact models handle classification and summarization locally.'),
('ai','Retrieval-augmented generation pitfalls','Chunking, ranking, and freshness issues that hurt answers.'),
('ai','AI regulation timelines firm up','Compliance deadlines affect model providers and deployers.'),
('ai','Structured outputs reduce parsing failures','Schema-constrained generation becomes widely available.'),
('ai','Inference cost per token keeps falling','Providers cut prices as hardware and batching improve.'),
('ai','Prompt caching cuts latency and spend','Reuse long prefixes across requests.'),
('ai','AI safety evaluations published for new releases','Providers share red-team results and mitigations.'),
('ai','Multimodal models handle documents natively','PDF and image understanding improve extraction pipelines.'),
('ai','Open-weight models narrow the gap','Community models approach proprietary quality on many tasks.'),
('ai','AI observability tooling matures','Trace prompts, tokens, and tool calls in production.'),
('ai','Fine-tuning versus prompting decision guide','When customization is worth the cost.'),
('ai','Model Context Protocol adoption grows','Standard tool interfaces ease integrations.'),
('ai','AI developer survey highlights trust gaps','Developers verify more than they accept.'),
('ai/models','New frontier model release improves long-context reasoning','Longer windows and better recall boost document workflows.'),
('ai/models','Model API adds batch discounts','Asynchronous batches lower cost for offline jobs.'),
('ai/models','Model deprecation schedule announced','Migrate before older versions retire.'),
('ai/models','Embedding models get multilingual upgrades','Better retrieval across languages.'),
('ai/models','Rate limit and quota changes','Tier updates affect high-volume apps.'),
('ai/models','Tool calling reliability improves','Fewer malformed arguments in function calls.'),
('ai/models','Speech and audio model APIs expand','Real-time voice features become simpler to build.'),
('ai/models','Image generation API updates','Higher fidelity and better text rendering.'),
('ai/models','Model pricing comparison','Cost per million tokens across major providers.'),
('ai/models','Streaming and latency tuning tips','Reduce time to first token.'),
('ai/models','Safety filters and moderation endpoints','New categories and thresholds.'),
('ai/models','Model version pinning guidance','Avoid silent behavior changes.'),
('ai/models','Reasoning models: when to use them','Trade latency for accuracy on hard tasks.'),
('ai/models','Provider status and incident reports','Reliability trends worth monitoring.'),
('ai/models','SDK updates for model providers','New client libraries add retries and types.'),
('ai/frameworks','PyTorch 2.x compiler improvements','Faster training and inference via graph compilation.'),
('ai/frameworks','JAX ecosystem updates','New libraries for large-scale training.'),
('ai/frameworks','LangChain and alternatives compared','Lightweight orchestration options gain favor.'),
('ai/frameworks','Hugging Face Transformers adds new architectures','Broader model support and quantization tools.'),
('ai/frameworks','ONNX Runtime performance gains','Faster cross-platform inference.'),
('ai/frameworks','vLLM and serving frameworks','Higher throughput with continuous batching.'),
('ai/frameworks','TensorFlow Lite updates for mobile','Smaller models and delegates.'),
('ai/frameworks','Agent frameworks maturity','Planning, memory, and tool use abstractions.'),
('ai/frameworks','Vector database client libraries','Choosing a store for embeddings.'),
('ai/frameworks','ML experiment tracking tools','Reproducibility with minimal overhead.'),
('ai/frameworks','Quantization techniques explained','Run larger models on modest hardware.'),
('ai/frameworks','Distributed training libraries','Sharding strategies for large models.'),
('ai/frameworks','MLOps pipelines in practice','Automate training, evaluation, and deployment.'),
('ai/frameworks','Evaluation libraries compared','Frameworks for LLM and classic ML tests.'),
('ai/frameworks','ML framework release digest','Notable changes across popular libraries.'),
('security','Memory safety roadmaps published by major vendors','Organizations commit to dates for secure-by-design transitions.'),
('security','Secrets scanning becomes default in code hosts','Push protection blocks leaked credentials earlier.'),
('security','SBOM requirements expand in procurement','Customers ask for software bills of materials.'),
('security','Phishing-resistant MFA mandates spread','Hardware keys and passkeys replace SMS codes.'),
('security','Threat modeling for small teams','Lightweight methods that fit sprint cycles.'),
('security','Zero-day exploitation trends report','Edge devices and VPNs remain prime targets.'),
('security','Security headers checklist','Practical defaults for modern web apps.'),
('security','Incident response playbook basics','Roles, communication, and evidence handling.'),
('security','Cloud misconfiguration findings','Public buckets and overbroad roles still lead.'),
('security','Application security testing tools compared','SAST, DAST, and SCA trade-offs.'),
('security','Data breach disclosure rules tighten','Shorter notification windows apply.'),
('security','Secure coding guidelines updated','Input validation and output encoding refresh.'),
('security','Bug bounty program trends','Payout and scope changes across platforms.'),
('security','Security training that works','Short, role-based exercises beat annual videos.'),
('security','Cryptography migration to post-quantum','Hybrid key exchange arrives in libraries.'),
('security/advisories','Critical remote code execution flaw in popular web framework','Patch immediately; exploit details are circulating.'),
('security/advisories','Actively exploited vulnerability added to KEV catalog','Federal agencies must remediate on a deadline.'),
('security/advisories','OpenSSL security release','Fixes for moderate-severity issues in several branches.'),
('security/advisories','Linux kernel privilege escalation patched','Distributions publish updated kernels.'),
('security/advisories','Router firmware vulnerability under attack','Update firmware and restrict management access.'),
('security/advisories','Container runtime escape vulnerability disclosed','Update runtimes on all nodes.'),
('security/advisories','Browser zero-day fixed in emergency update','Restart browsers to apply the fix.'),
('security/advisories','Database server authentication bypass','Upgrade to the patched release.'),
('security/advisories','VPN appliance critical flaw','Apply vendor mitigation and rotate credentials.'),
('security/advisories','Java deserialization issue in widely used library','Upgrade or disable the vulnerable feature.'),
('security/advisories','Windows monthly patch Tuesday summary','Several critical and exploited fixes.'),
('security/advisories','CI/CD tool vulnerability exposes secrets','Rotate tokens and update agents.'),
('security/advisories','Mail server vulnerability enables takeover','Patch and review logs for compromise.'),
('security/advisories','Mobile OS security bulletin','Monthly fixes for kernel and media components.'),
('security/advisories','CVE scoring changes and what they mean','Understand CVSS v4 metrics.'),
('security/supply-chain','Malicious packages found in npm and PyPI','Typosquatting campaigns target developer machines.'),
('security/supply-chain','Maintainer account takeover prompts mandatory 2FA','Registries tighten publisher requirements.'),
('security/supply-chain','Build provenance with SLSA explained','Verify artifacts back to source.'),
('security/supply-chain','Dependency pinning versus automatic updates','Balance safety and freshness.'),
('security/supply-chain','GitHub Actions hardening guide','Pin actions by SHA and limit token scope.'),
('security/supply-chain','Signed container images with Sigstore','Verify signatures at deploy time.'),
('security/supply-chain','Open-source maintainer burnout and risk','Funding gaps raise security concerns.'),
('security/supply-chain','Compromised build tool update','Teams audit pipelines after a poisoned release.'),
('security/supply-chain','Package registry malware scanning improves','Automated detection catches more samples.'),
('security/supply-chain','Typosquatting defenses for developers','Check names and publisher history.'),
('security/supply-chain','Reproducible builds help detect tampering','Compare outputs across builders.'),
('security/supply-chain','Vendor risk assessments for software','Questions to ask your suppliers.'),
('security/supply-chain','Lockfile review in pull requests','Spot suspicious dependency changes.'),
('security/supply-chain','Private registries and mirrors','Reduce exposure to public package outages.'),
('security/supply-chain','Supply chain attack timeline recap','Lessons from recent high-profile incidents.'),
('security/incidents','Large retailer discloses customer data breach','Attackers accessed a support system using stolen credentials.'),
('security/incidents','Ransomware gang targets healthcare providers','Hospitals report disrupted operations.'),
('security/incidents','Cloud provider outage traced to configuration change','Postmortem details rollout safeguards.'),
('security/incidents','Social engineering attack bypasses help desk','Verification procedures tighten afterward.'),
('security/incidents','Source code repository leak investigated','Internal secrets rotated as a precaution.'),
('security/incidents','Open-source project breach postmortem','Compromised token led to a malicious release.'),
('security/incidents','DDoS attacks hit record volumes','Mitigation providers report new peaks.'),
('security/incidents','Third-party analytics script compromised','Payment pages affected on many sites.'),
('security/incidents','Password manager incident review','Transparent timeline and customer guidance.'),
('security/incidents','Telecom breach exposes call metadata','Regulators open an inquiry.'),
('security/incidents','Insider threat case study','Access reviews would have caught the activity.'),
('security/incidents','Crypto exchange hack losses','Funds traced across multiple chains.'),
('security/incidents','Government agency email compromise','Token theft enabled mailbox access.'),
('security/incidents','Breach notification lessons learned','What good communication looks like.'),
('security/incidents','Incident response retrospectives','Common themes in public postmortems.'),
('devtools','Developer productivity metrics debate continues','Teams look beyond lines of code and velocity.'),
('devtools','Terminal emulators and shells see a revival','GPU-accelerated terminals and modern shells gain fans.'),
('devtools','Monorepo tooling comparison','Bazel, Nx, and Turborepo trade-offs.'),
('devtools','Local development environments in containers','Dev containers standardize setups.'),
('devtools','Feature flags best practices','Flag lifecycle and cleanup matter.'),
('devtools','API design tooling roundup','OpenAPI-first workflows speed teams up.'),
('devtools','Git workflow trends','Trunk-based development gains share.'),
('devtools','Debugging tools you should know','Time-travel and record-replay options.'),
('devtools','Code review automation','Bots handle style so humans focus on design.'),
('devtools','Package manager speed benchmarks','Install time comparisons across tools.'),
('devtools','Documentation as code workflows','Keep docs next to source.'),
('devtools','Observability for developers','Tracing locally before production.'),
('devtools','Developer portals and catalogs','Backstage-style catalogs spread.'),
('devtools','Database GUI and CLI tools','Productive clients for everyday queries.'),
('devtools','Developer tooling survey','Most-loved and most-dreaded tools.'),
('devtools/github','GitHub Actions adds larger runners and caching improvements','Faster builds with new cache backends.'),
('devtools/github','GitHub Copilot expands agent mode','Multi-step tasks run with review checkpoints.'),
('devtools/github','GitHub secret scanning push protection expands','More token types detected before commit.'),
('devtools/github','GitHub merge queue improvements','Fewer broken main branches.'),
('devtools/github','GitHub code search upgrades','Symbol navigation across repositories.'),
('devtools/github','GitHub Projects automation','Workflows move issues without manual updates.'),
('devtools/github','GitHub Pages and deployment changes','New deployment options and limits.'),
('devtools/github','GitHub security advisories workflow','Coordinate private fixes before disclosure.'),
('devtools/github','GitHub Codespaces cost control','Idle timeouts and prebuilds.'),
('devtools/github','GitHub rulesets replace branch protection','Org-wide policies simplify governance.'),
('devtools/github','GitHub CLI tips','Scripts and aliases to save time.'),
('devtools/github','GitHub Dependabot grouping','Fewer noisy update pull requests.'),
('devtools/github','GitHub API rate limit changes','Plan integrations around new limits.'),
('devtools/github','GitHub Actions security: OIDC to cloud','Replace long-lived cloud keys.'),
('devtools/github','GitHub changelog digest','Notable platform updates this month.'),
('devtools/editors','VS Code adds new AI editing features','Inline edits and chat improvements reach stable.'),
('devtools/editors','JetBrains IDEs update for the new year','Performance and language support upgrades.'),
('devtools/editors','Neovim 0.11 improves LSP defaults','Better out-of-box language features.'),
('devtools/editors','Zed editor collaboration features','Multiplayer editing gets polished.'),
('devtools/editors','VS Code extension security guidance','Review permissions and publishers.'),
('devtools/editors','Editor config and formatting standards','Keep teams consistent with shared settings.'),
('devtools/editors','Remote development in editors','SSH and container workflows compared.'),
('devtools/editors','Debugger integrations improve','Breakpoints and variable views across languages.'),
('devtools/editors','Vim motions in every editor','Bindings spread across IDEs.'),
('devtools/editors','Editor startup time benchmarks','Lightweight options compared.'),
('devtools/editors','Language server protocol updates','New features expand editor capabilities.'),
('devtools/editors','Snippet and template productivity tips','Automate boilerplate.'),
('devtools/editors','Editor themes and accessibility','High-contrast options for long sessions.'),
('devtools/editors','Terminal inside the editor','Integrated terminals gain features.'),
('devtools/editors','Editor release notes digest','Highlights from popular editors.'),
('devtools/ci-cd','CI pipelines get faster with remote caching','Shared caches slash repeated build work.'),
('devtools/ci-cd','CI test sharding and flaky test handling','Quarantine unreliable tests automatically.'),
('devtools/ci-cd','Deployment strategies explained','Blue/green, canary, and rolling releases.'),
('devtools/ci-cd','GitOps tools compared','Argo CD and Flux in production.'),
('devtools/ci-cd','CI secrets management best practices','Short-lived credentials and scoped access.'),
('devtools/ci-cd','Preview environments per pull request','Test changes in isolated deployments.'),
('devtools/ci-cd','CI cost optimization','Right-size runners and cancel redundant jobs.'),
('devtools/ci-cd','Release automation with conventional commits','Version and changelog generation.'),
('devtools/ci-cd','Self-hosted runners security','Isolate and patch build agents.'),
('devtools/ci-cd','Pipeline as code patterns','Reusable workflows and templates.'),
('devtools/ci-cd','Build observability','Track duration and failure trends.'),
('devtools/ci-cd','Container build pipelines','Cache layers and multi-arch images.'),
('devtools/ci-cd','Progressive delivery with feature flags','Decouple deploy from release.'),
('devtools/ci-cd','CI platform comparison','Features and pricing across vendors.'),
('devtools/ci-cd','CI/CD release notes digest','Updates from popular platforms.');

CREATE TEMP TABLE seed_numbered ON COMMIT DROP AS
SELECT i.*, row_number() OVER (PARTITION BY topic_slug ORDER BY id) AS n,
       topic_slug || '#' || row_number() OVER (PARTITION BY topic_slug ORDER BY id) AS seed_key
FROM seed_items i;

INSERT INTO stories (title, summary, body_md, kind, severity, importance, published_at,
                     dedupe_keys, model, prompt_version, notified_at)
SELECT
    s.title,
    s.summary,
    '## ' || s.title || E'\n\n' || s.summary || E'\n\n'
        || E'### Why it matters\n\nChanges like this ripple through build pipelines, dependencies and on-call routines. Skimming the details now is cheaper than debugging a surprise later.\n\n'
        || E'### What to do next\n\n- Read the upstream release notes or advisory.\n- Try the change in a staging environment.\n- Roll it out gradually and watch your dashboards.\n',
    k.kind,
    CASE WHEN k.kind = 'security' THEN (ARRAY['low', 'medium', 'high', 'critical'])[1 + (s.n % 4)::int] END,
    (1 + (s.n * 7 + length(s.title)) % 5)::smallint,
    now() - (s.n * 9 + s.id % 7) * interval '1 hour',
    jsonb_build_object('seed', s.seed_key),
    'seed',
    'seed',
    now()
FROM seed_numbered s
CROSS JOIN LATERAL (
    SELECT CASE
        WHEN s.topic_slug LIKE 'security%' AND s.n % 3 = 0 THEN 'security'
        ELSE (ARRAY['release', 'announcement', 'article', 'breaking', 'deprecation', 'release'])[1 + (s.n % 6)::int]
    END AS kind
) k
WHERE NOT EXISTS (SELECT 1 FROM stories x WHERE x.dedupe_keys->>'seed' = s.seed_key);

INSERT INTO story_topics (story_id, topic_id)
SELECT st.id, t.id
FROM seed_numbered s
JOIN stories st ON st.dedupe_keys->>'seed' = s.seed_key
JOIN topics t ON t.slug = s.topic_slug
ON CONFLICT DO NOTHING;

INSERT INTO story_sources (story_id, url, source_name)
SELECT st.id, 'https://example.com/seed/' || s.topic_slug || '/' || s.n, 'Changeloom Seed'
FROM seed_numbered s
JOIN stories st ON st.dedupe_keys->>'seed' = s.seed_key
ON CONFLICT DO NOTHING;

COMMIT;
