//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Severity.
const (
	Critical Severity = "critical"
	High     Severity = "high"
	Low      Severity = "low"
	Medium   Severity = "medium"
)

// Valid indicates whether the value is a known member of the Severity enum.
func (e Severity) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for StoryMatch.
const (
	StoryMatchExplore    StoryMatch = "explore"
	StoryMatchFollowed   StoryMatch = "followed"
	StoryMatchProfession StoryMatch = "profession"
	StoryMatchRelated    StoryMatch = "related"
)

// Valid indicates whether the value is a known member of the StoryMatch enum.
func (e StoryMatch) Valid() bool {
	switch e {
	case StoryMatchExplore:
		return true
	case StoryMatchFollowed:
		return true
	case StoryMatchProfession:
		return true
	case StoryMatchRelated:
		return true
	default:
		return false
	}
}

// Defines values for StoryKind.
const (
	Announcement StoryKind = "announcement"
	Article      StoryKind = "article"
	Breaking     StoryKind = "breaking"
	Deal         StoryKind = "deal"
	Deprecation  StoryKind = "deprecation"
	Policy       StoryKind = "policy"
	Release      StoryKind = "release"
	Research     StoryKind = "research"
	Security     StoryKind = "security"
)

// Valid indicates whether the value is a known member of the StoryKind enum.
func (e StoryKind) Valid() bool {
	switch e {
	case Announcement:
		return true
	case Article:
		return true
	case Breaking:
		return true
	case Deal:
		return true
	case Deprecation:
		return true
	case Policy:
		return true
	case Release:
		return true
	case Research:
		return true
	case Security:
		return true
	default:
		return false
	}
}

// Defines values for StorySummaryMatch.
const (
	StorySummaryMatchExplore    StorySummaryMatch = "explore"
	StorySummaryMatchFollowed   StorySummaryMatch = "followed"
	StorySummaryMatchProfession StorySummaryMatch = "profession"
	StorySummaryMatchRelated    StorySummaryMatch = "related"
)

// Valid indicates whether the value is a known member of the StorySummaryMatch enum.
func (e StorySummaryMatch) Valid() bool {
	switch e {
	case StorySummaryMatchExplore:
		return true
	case StorySummaryMatchFollowed:
		return true
	case StorySummaryMatchProfession:
		return true
	case StorySummaryMatchRelated:
		return true
	default:
		return false
	}
}

// Defines values for TopicRequestStatus.
const (
	Accepted TopicRequestStatus = "accepted"
	Merged   TopicRequestStatus = "merged"
	Pending  TopicRequestStatus = "pending"
	Rejected TopicRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TopicRequestStatus enum.
func (e TopicRequestStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Merged:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for PutMyDeviceJSONBodyPlatform.
const (
	Android PutMyDeviceJSONBodyPlatform = "android"
	Ios     PutMyDeviceJSONBodyPlatform = "ios"
)

// Valid indicates whether the value is a known member of the PutMyDeviceJSONBodyPlatform enum.
func (e PutMyDeviceJSONBodyPlatform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Example: not_found
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Me defines model for Me.
type Me struct {
	// Country ISO 3166-1 alpha-2 country the user chose; absent until set.
	Country *string `json:"country,omitempty"`
	Email   *string `json:"email,omitempty"`
	Id      int64   `json:"id"`

	// Professions Profession slugs.
	Professions []string `json:"professions"`
	Stats       MeStats  `json:"stats"`

	// Topics Followed topic slugs.
	Topics []string `json:"topics"`
}

// MeStats defines model for MeStats.
type MeStats struct {
	// Read Number of stories marked read.
	Read int64 `json:"read"`

	// Saved Number of bookmarked stories.
	Saved int64 `json:"saved"`
}

// Profession defines model for Profession.
type Profession struct {
	Description string `json:"description"`

	// Name Example: Software Engineer
	Name string `json:"name"`

	// Slug Example: software-engineer
	Slug string `json:"slug"`

	// Topics Root topic slugs (areas), in display order.
	Topics []string `json:"topics"`
}

// Severity defines model for Severity.
type Severity string

// Story defines model for Story.
type Story struct {
	// BodyMd Markdown body.
	BodyMd       string    `json:"body_md"`
	Id           int64     `json:"id"`
	Importance   int       `json:"importance"`
	IsBookmarked bool      `json:"is_bookmarked"`
	IsRead       bool      `json:"is_read"`
	Kind         StoryKind `json:"kind"`

	// Match Timeline only: whether the story is in a followed topic, an area of one of the user's professions, a topic related to a followed one, or none of these.
	Match       *StoryMatch   `json:"match,omitempty"`
	PublishedAt time.Time     `json:"published_at"`
	ReadAt      *time.Time    `json:"read_at,omitempty"`
	Severity    *Severity     `json:"severity,omitempty"`
	Sources     []StorySource `json:"sources"`
	Summary     string        `json:"summary"`
	Title       string        `json:"title"`
	Topics      []string      `json:"topics"`
}

// StoryMatch Timeline only: whether the story is in a followed topic, an area of one of the user's professions, a topic related to a followed one, or none of these.
type StoryMatch string

// StoryKind defines model for StoryKind.
type StoryKind string

// StorySource defines model for StorySource.
type StorySource struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

// StorySummary defines model for StorySummary.
type StorySummary struct {
	Id           int64     `json:"id"`
	Importance   int       `json:"importance"`
	IsBookmarked bool      `json:"is_bookmarked"`
	IsRead       bool      `json:"is_read"`
	Kind         StoryKind `json:"kind"`

	// Match Timeline only: whether the story is in a followed topic, an area of one of the user's professions, a topic related to a followed one, or none of these.
	Match       *StorySummaryMatch `json:"match,omitempty"`
	PublishedAt time.Time          `json:"published_at"`
	ReadAt      *time.Time         `json:"read_at,omitempty"`
	Severity    *Severity          `json:"severity,omitempty"`
	Summary     string             `json:"summary"`
	Title       string             `json:"title"`
	Topics      []string           `json:"topics"`
}

// StorySummaryMatch Timeline only: whether the story is in a followed topic, an area of one of the user's professions, a topic related to a followed one, or none of these.
type StorySummaryMatch string

// Topic defines model for Topic.
type Topic struct {
	Description string `json:"description"`

	// Name Example: Go
	Name string `json:"name"`

	// Parent Parent topic slug; absent for root topics.
	Parent *string `json:"parent,omitempty"`

	// Slug Example: languages/go
	Slug string `json:"slug"`
}

// TopicRequest defines model for TopicRequest.
type TopicRequest struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`

	// Note Reviewer note.
	Note       *string    `json:"note,omitempty"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`

	// Status accepted means a new topic was created; merged means it maps to an existing one.
	Status TopicRequestStatus `json:"status"`
	Text   string             `json:"text"`

	// Topic Slug of the topic the request was resolved to.
	Topic *string `json:"topic,omitempty"`
}

// TopicRequestStatus accepted means a new topic was created; merged means it maps to an existing one.
type TopicRequestStatus string

// StoryID defines model for StoryID.
type StoryID = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// StoryPage defines model for StoryPage.
type StoryPage struct {
	Items []StorySummary `json:"items"`

	// NextCursor Absent when there are no more pages.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListBookmarksParams defines parameters for ListBookmarks.
type ListBookmarksParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SyncBookmarksJSONBody defines parameters for SyncBookmarks.
type SyncBookmarksJSONBody struct {
	Add    []int64 `json:"add"`
	Remove []int64 `json:"remove"`
}

// PutMyCountryJSONBody defines parameters for PutMyCountry.
type PutMyCountryJSONBody struct {
	// Country ISO 3166-1 alpha-2 code, upper case.
	Country *string `json:"country"`
}

// DeleteMyDeviceParams defines parameters for DeleteMyDevice.
type DeleteMyDeviceParams struct {
	Token string `form:"token" json:"token"`
}

// PutMyDeviceJSONBody defines parameters for PutMyDevice.
type PutMyDeviceJSONBody struct {
	Platform PutMyDeviceJSONBodyPlatform `json:"platform"`

	// Token FCM registration token.
	Token string `json:"token"`
}

// PutMyDeviceJSONBodyPlatform defines parameters for PutMyDevice.
type PutMyDeviceJSONBodyPlatform string

// PutMyProfessionsJSONBody defines parameters for PutMyProfessions.
type PutMyProfessionsJSONBody struct {
	// Professions Profession slugs.
	Professions []string `json:"professions"`
}

// PutMyTopicsJSONBody defines parameters for PutMyTopics.
type PutMyTopicsJSONBody struct {
	// Topics Topic slugs to follow.
	Topics []string `json:"topics"`
}

// SearchStoriesParams defines parameters for SearchStories.
type SearchStoriesParams struct {
	// Q Search text (web-search syntax; quotes and `-word` are supported).
	Q      string  `form:"q" json:"q"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// RecordStoryViewsJSONBody defines parameters for RecordStoryViews.
type RecordStoryViewsJSONBody struct {
	Ids []int64 `json:"ids"`
}

// GetTimelineParams defines parameters for GetTimeline.
type GetTimelineParams struct {
	// Cursor Opaque `next_cursor` from the previous page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// Kind Only stories of these kinds (repeat the parameter for several). Absent means every kind.
	Kind *[]StoryKind `form:"kind,omitempty" json:"kind,omitempty"`

	// Read `true` returns only read stories, `false` only unread ones. Absent returns both.
	Read *bool `form:"read,omitempty" json:"read,omitempty"`
}

// CreateTopicRequestJSONBody defines parameters for CreateTopicRequest.
type CreateTopicRequestJSONBody struct {
	// Text What to follow, 2-100 characters after trimming.
	Text string `json:"text"`
}

// SyncBookmarksJSONRequestBody defines body for SyncBookmarks for application/json ContentType.
type SyncBookmarksJSONRequestBody SyncBookmarksJSONBody

// PutMyCountryJSONRequestBody defines body for PutMyCountry for application/json ContentType.
type PutMyCountryJSONRequestBody PutMyCountryJSONBody

// PutMyDeviceJSONRequestBody defines body for PutMyDevice for application/json ContentType.
type PutMyDeviceJSONRequestBody PutMyDeviceJSONBody

// PutMyProfessionsJSONRequestBody defines body for PutMyProfessions for application/json ContentType.
type PutMyProfessionsJSONRequestBody PutMyProfessionsJSONBody

// PutMyTopicsJSONRequestBody defines body for PutMyTopics for application/json ContentType.
type PutMyTopicsJSONRequestBody PutMyTopicsJSONBody

// RecordStoryViewsJSONRequestBody defines body for RecordStoryViews for application/json ContentType.
type RecordStoryViewsJSONRequestBody RecordStoryViewsJSONBody

// CreateTopicRequestJSONRequestBody defines body for CreateTopicRequest for application/json ContentType.
type CreateTopicRequestJSONRequestBody CreateTopicRequestJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)

	// (GET /ready)
	GetReady(w http.ResponseWriter, r *http.Request)
	// ListBookmarks Bookmarked stories, most recently bookmarked first.
	// (GET /v1/bookmarks)
	ListBookmarks(w http.ResponseWriter, r *http.Request, params ListBookmarksParams)
	// SyncBookmarks Apply a batch of bookmark additions and removals (idempotent).
	// (POST /v1/bookmarks/sync)
	SyncBookmarks(w http.ResponseWriter, r *http.Request)
	// DeleteMe Delete the signed-in user's account data.
	// (DELETE /v1/me)
	DeleteMe(w http.ResponseWriter, r *http.Request)
	// GetMe Get the signed-in user.
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// PutMyCountry Set (or clear) the user's country.
	// (PUT /v1/me/country)
	PutMyCountry(w http.ResponseWriter, r *http.Request)
	// DeleteMyDevice Unregister a push notification token (idempotent).
	// (DELETE /v1/me/devices)
	DeleteMyDevice(w http.ResponseWriter, r *http.Request, params DeleteMyDeviceParams)
	// PutMyDevice Register (or refresh) a push notification token for this device.
	// (PUT /v1/me/devices)
	PutMyDevice(w http.ResponseWriter, r *http.Request)
	// PutMyProfessions Replace the user's professions.
	// (PUT /v1/me/professions)
	PutMyProfessions(w http.ResponseWriter, r *http.Request)
	// PutMyTopics Replace the set of followed topics.
	// (PUT /v1/me/topics)
	PutMyTopics(w http.ResponseWriter, r *http.Request)
	// SearchStories Full-text search over all stories, newest first; titles also match fuzzily.
	// (GET /v1/search)
	SearchStories(w http.ResponseWriter, r *http.Request, params SearchStoriesParams)
	// RecordStoryViews Record stories that were visible in the user's feed (idempotent).
	// (POST /v1/stories/views)
	RecordStoryViews(w http.ResponseWriter, r *http.Request)
	// GetStory Get a story with its full body and sources.
	// (GET /v1/stories/{id})
	GetStory(w http.ResponseWriter, r *http.Request, id StoryID)
	// RemoveBookmark Remove a bookmark (idempotent).
	// (DELETE /v1/stories/{id}/bookmark)
	RemoveBookmark(w http.ResponseWriter, r *http.Request, id StoryID)
	// AddBookmark Bookmark a story (idempotent).
	// (PUT /v1/stories/{id}/bookmark)
	AddBookmark(w http.ResponseWriter, r *http.Request, id StoryID)
	// MarkStoryUnread Mark a story unread (idempotent).
	// (DELETE /v1/stories/{id}/read)
	MarkStoryUnread(w http.ResponseWriter, r *http.Request, id StoryID)
	// MarkStoryRead Mark a story read (idempotent; keeps the first read time).
	// (PUT /v1/stories/{id}/read)
	MarkStoryRead(w http.ResponseWriter, r *http.Request, id StoryID)
	// GetTimeline Recent stories ranked by interest.
	// (GET /v1/timeline)
	GetTimeline(w http.ResponseWriter, r *http.Request, params GetTimelineParams)
	// ListMyTopicRequests The signed-in user's topic requests, newest first.
	// (GET /v1/topic-requests)
	ListMyTopicRequests(w http.ResponseWriter, r *http.Request)
	// CreateTopicRequest Ask for a topic to be added to the catalog.
	// (POST /v1/topic-requests)
	CreateTopicRequest(w http.ResponseWriter, r *http.Request)
	// ListTopics List all topics.
	// (GET /v1/topics)
	ListTopics(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBookmarks operation middleware
func (siw *ServerInterfaceWrapper) ListBookmarks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookmarksParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookmarks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncBookmarks operation middleware
func (siw *ServerInterfaceWrapper) SyncBookmarks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncBookmarks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMyCountry operation middleware
func (siw *ServerInterfaceWrapper) PutMyCountry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMyCountry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMyDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteMyDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteMyDeviceParams

	// ------------- Required query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMyDevice(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMyDevice operation middleware
func (siw *ServerInterfaceWrapper) PutMyDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMyDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMyProfessions operation middleware
func (siw *ServerInterfaceWrapper) PutMyProfessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMyProfessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMyTopics operation middleware
func (siw *ServerInterfaceWrapper) PutMyTopics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMyTopics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchStories operation middleware
func (siw *ServerInterfaceWrapper) SearchStories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchStoriesParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchStories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordStoryViews operation middleware
func (siw *ServerInterfaceWrapper) RecordStoryViews(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordStoryViews(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStory operation middleware
func (siw *ServerInterfaceWrapper) GetStory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StoryID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveBookmark operation middleware
func (siw *ServerInterfaceWrapper) RemoveBookmark(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StoryID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBookmark operation middleware
func (siw *ServerInterfaceWrapper) AddBookmark(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StoryID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkStoryUnread operation middleware
func (siw *ServerInterfaceWrapper) MarkStoryUnread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StoryID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkStoryUnread(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkStoryRead operation middleware
func (siw *ServerInterfaceWrapper) MarkStoryRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StoryID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkStoryRead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimelineParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "read" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "read", r.URL.Query(), &params.Read, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "read"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "read", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeline(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyTopicRequests operation middleware
func (siw *ServerInterfaceWrapper) ListMyTopicRequests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyTopicRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTopicRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateTopicRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTopicRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopics operation middleware
func (siw *ServerInterfaceWrapper) ListTopics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ready", wrapper.GetReady)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/topics", wrapper.ListTopics)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/me", wrapper.DeleteMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/me/topics", wrapper.PutMyTopics)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/me/professions", wrapper.PutMyProfessions)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/me/country", wrapper.PutMyCountry)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/me/devices", wrapper.DeleteMyDevice)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/me/devices", wrapper.PutMyDevice)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/timeline", wrapper.GetTimeline)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/stories/{id}", wrapper.GetStory)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/stories/{id}/read", wrapper.MarkStoryUnread)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/stories/{id}/read", wrapper.MarkStoryRead)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/search", wrapper.SearchStories)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/bookmarks", wrapper.ListBookmarks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/bookmarks/sync", wrapper.SyncBookmarks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/stories/views", wrapper.RecordStoryViews)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/stories/{id}/bookmark", wrapper.RemoveBookmark)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/stories/{id}/bookmark", wrapper.AddBookmark)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/topic-requests", wrapper.ListMyTopicRequests)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/topic-requests", wrapper.CreateTopicRequest)

	return m
}
