// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clean.sql

package db

import (
	"context"
)

const countStoriesOnlyIn = `-- name: CountStoriesOnlyIn :one
SELECT count(*)::bigint
FROM stories s
WHERE EXISTS (
        SELECT 1 FROM story_topics st JOIN topics t ON t.id = st.topic_id
        WHERE st.story_id = s.id AND t.slug = ANY($1::text[])
    )
    AND NOT EXISTS (
        SELECT 1 FROM story_topics st JOIN topics t ON t.id = st.topic_id
        WHERE st.story_id = s.id AND NOT (t.slug = ANY($1::text[]))
    )
    AND NOT EXISTS (SELECT 1 FROM user_bookmarks b WHERE b.story_id = s.id)
`

// Stories every one of whose topics is in @slugs and that nobody saved.
func (q *Queries) CountStoriesOnlyIn(ctx context.Context, slugs []string) (int64, error) {
	row := q.db.QueryRow(ctx, countStoriesOnlyIn, slugs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteChildTopicsBySlug = `-- name: DeleteChildTopicsBySlug :execrows
DELETE FROM topics WHERE slug = ANY($1::text[]) AND parent_id IS NOT NULL
`

func (q *Queries) DeleteChildTopicsBySlug(ctx context.Context, slugs []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChildTopicsBySlug, slugs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfessionsBySlug = `-- name: DeleteProfessionsBySlug :execrows
DELETE FROM professions WHERE slug = ANY($1::text[])
`

func (q *Queries) DeleteProfessionsBySlug(ctx context.Context, slugs []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfessionsBySlug, slugs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRootTopicsBySlug = `-- name: DeleteRootTopicsBySlug :execrows
DELETE FROM topics WHERE slug = ANY($1::text[]) AND parent_id IS NULL
`

func (q *Queries) DeleteRootTopicsBySlug(ctx context.Context, slugs []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRootTopicsBySlug, slugs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStoriesOnlyIn = `-- name: DeleteStoriesOnlyIn :execrows
DELETE FROM stories
WHERE id IN (
    SELECT s.id FROM stories s
    WHERE EXISTS (
            SELECT 1 FROM story_topics st JOIN topics t ON t.id = st.topic_id
            WHERE st.story_id = s.id AND t.slug = ANY($1::text[])
        )
        AND NOT EXISTS (
            SELECT 1 FROM story_topics st JOIN topics t ON t.id = st.topic_id
            WHERE st.story_id = s.id AND NOT (t.slug = ANY($1::text[]))
        )
        AND NOT EXISTS (SELECT 1 FROM user_bookmarks b WHERE b.story_id = s.id)
    ORDER BY s.id
    LIMIT $2
)
`

type DeleteStoriesOnlyInParams struct {
	Slugs   []string
	MaxRows int32
}

// Deletes at most @max_rows of the stories CountStoriesOnlyIn counts. Sources, topics, views and
// read state cascade.
func (q *Queries) DeleteStoriesOnlyIn(ctx context.Context, arg DeleteStoriesOnlyInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStoriesOnlyIn, arg.Slugs, arg.MaxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllProfessionSlugs = `-- name: ListAllProfessionSlugs :many
SELECT slug FROM professions ORDER BY slug
`

func (q *Queries) ListAllProfessionSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllProfessionSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostedProfessionsInUse = `-- name: ListHostedProfessionsInUse :many
SELECT p.slug
FROM professions p
WHERE EXISTS (SELECT 1 FROM user_professions up WHERE up.profession_id = p.id)
ORDER BY p.slug
`

// Run against a hosted DB: professions a user picked.
func (q *Queries) ListHostedProfessionsInUse(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listHostedProfessionsInUse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostedTopicsInUse = `-- name: ListHostedTopicsInUse :many
SELECT t.slug
FROM topics t
WHERE EXISTS (SELECT 1 FROM user_topics ut WHERE ut.topic_id = t.id)
    OR EXISTS (SELECT 1 FROM user_topic_mutes um WHERE um.topic_id = t.id)
    OR EXISTS (SELECT 1 FROM topic_requests r WHERE r.topic_id = t.id)
ORDER BY t.slug
`

// Run against a hosted DB: topics a user follows or muted, or that a topic request resolved to.
func (q *Queries) ListHostedTopicsInUse(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listHostedTopicsInUse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestedTopicSlugs = `-- name: ListRequestedTopicSlugs :many
SELECT DISTINCT topic_slug::text AS slug FROM request_inbox WHERE topic_slug IS NOT NULL ORDER BY 1
`

// Topics a request in the local inbox resolved to: created for (or merged into) a user's request.
func (q *Queries) ListRequestedTopicSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequestedTopicSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicTree = `-- name: ListTopicTree :many
SELECT t.slug, p.slug AS parent_slug
FROM topics t
LEFT JOIN topics p ON p.id = t.parent_id
ORDER BY t.slug
`

type ListTopicTreeRow struct {
	Slug       string
	ParentSlug *string
}

// Every topic with its parent's slug, local or hosted.
func (q *Queries) ListTopicTree(ctx context.Context) ([]ListTopicTreeRow, error) {
	rows, err := q.db.Query(ctx, listTopicTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicTreeRow{}
	for rows.Next() {
		var i ListTopicTreeRow
		if err := rows.Scan(&i.Slug, &i.ParentSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
