// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetch.sql

package db

import (
	"context"
	"time"
)

const addStorySource = `-- name: AddStorySource :exec
INSERT INTO story_sources (story_id, url, source_name)
VALUES ($1, $2, $3)
ON CONFLICT (story_id, url) DO NOTHING
`

type AddStorySourceParams struct {
	StoryID    int64
	Url        string
	SourceName string
}

func (q *Queries) AddStorySource(ctx context.Context, arg AddStorySourceParams) error {
	_, err := q.db.Exec(ctx, addStorySource, arg.StoryID, arg.Url, arg.SourceName)
	return err
}

const addStoryTopics = `-- name: AddStoryTopics :exec
INSERT INTO story_topics (story_id, topic_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddStoryTopicsParams struct {
	StoryID  int64
	TopicIds []int64
}

func (q *Queries) AddStoryTopics(ctx context.Context, arg AddStoryTopicsParams) error {
	_, err := q.db.Exec(ctx, addStoryTopics, arg.StoryID, arg.TopicIds)
	return err
}

const findMergeTarget = `-- name: FindMergeTarget :one
SELECT id FROM stories
WHERE published_at >= $1
    AND (countries && $2::text[] OR (cardinality(countries) = 0 AND cardinality($2::text[]) = 0))
    AND (
        EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(dedupe_keys -> 'cve_ids') c
            WHERE c = ANY($3::text[])
        )
        OR (
            $4::text <> '' AND $5::text <> ''
            AND dedupe_keys ->> 'project' = $4::text
            AND dedupe_keys ->> 'version' = $5::text
        )
    )
ORDER BY published_at DESC, id DESC
LIMIT 1
`

type FindMergeTargetParams struct {
	Since     time.Time
	Countries []string
	CveIds    []string
	Project   string
	Version   string
}

// A recent story about the same CVE, or the same project and version, for the same countries.
func (q *Queries) FindMergeTarget(ctx context.Context, arg FindMergeTargetParams) (int64, error) {
	row := q.db.QueryRow(ctx, findMergeTarget,
		arg.Since,
		arg.Countries,
		arg.CveIds,
		arg.Project,
		arg.Version,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findStoryBySourceURL = `-- name: FindStoryBySourceURL :one
SELECT story_id FROM story_sources
JOIN stories s ON s.id = story_id
WHERE url = ANY($1::text[])
    AND NOT story_id = ANY($2::bigint[])
    AND (s.countries && $3::text[] OR (cardinality(s.countries) = 0 AND cardinality($3::text[]) = 0))
ORDER BY story_id DESC
LIMIT 1
`

type FindStoryBySourceURLParams struct {
	Urls       []string
	ExcludeIds []int64
	Countries  []string
}

func (q *Queries) FindStoryBySourceURL(ctx context.Context, arg FindStoryBySourceURLParams) (int64, error) {
	row := q.db.QueryRow(ctx, findStoryBySourceURL, arg.Urls, arg.ExcludeIds, arg.Countries)
	var story_id int64
	err := row.Scan(&story_id)
	return story_id, err
}

const finishFetchRun = `-- name: FinishFetchRun :exec
UPDATE fetch_runs
SET status = $1,
    finished_at = now(),
    stories_added = $2,
    error = $3,
    cost_usd = $4
WHERE id = $5
`

type FinishFetchRunParams struct {
	Status       string
	StoriesAdded int32
	Error        *string
	CostUsd      *float64
	ID           int64
}

func (q *Queries) FinishFetchRun(ctx context.Context, arg FinishFetchRunParams) error {
	_, err := q.db.Exec(ctx, finishFetchRun,
		arg.Status,
		arg.StoriesAdded,
		arg.Error,
		arg.CostUsd,
		arg.ID,
	)
	return err
}

const insertStory = `-- name: InsertStory :one
INSERT INTO stories (title, summary, body_md, kind, severity, importance, published_at, dedupe_keys, model, prompt_version, countries)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::text[])
RETURNING id
`

type InsertStoryParams struct {
	Title         string
	Summary       string
	BodyMd        string
	Kind          string
	Severity      *string
	Importance    int16
	PublishedAt   time.Time
	DedupeKeys    []byte
	Model         string
	PromptVersion string
	Countries     []string
}

func (q *Queries) InsertStory(ctx context.Context, arg InsertStoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStory,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.Kind,
		arg.Severity,
		arg.Importance,
		arg.PublishedAt,
		arg.DedupeKeys,
		arg.Model,
		arg.PromptVersion,
		arg.Countries,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveCountries = `-- name: ListActiveCountries :many
SELECT country, sum(users)::integer AS users
FROM country_stats
GROUP BY country
ORDER BY sum(users) DESC, country
LIMIT $1
`

type ListActiveCountriesRow struct {
	Country string
	Users   int32
}

// Countries with users, summed over the hosted envs, the most users first.
func (q *Queries) ListActiveCountries(ctx context.Context, maxRows int32) ([]ListActiveCountriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCountries, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCountriesRow{}
	for rows.Next() {
		var i ListActiveCountriesRow
		if err := rows.Scan(&i.Country, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountryFetches = `-- name: ListCountryFetches :many
SELECT tid::bigint AS topic_id, fr.country::text AS country, max(fr.started_at)::timestamptz AS last_fetched_at
FROM fetch_runs fr, unnest(fr.topic_ids) AS tid
WHERE fr.status = 'succeeded' AND fr.country IS NOT NULL
GROUP BY tid, fr.country
`

type ListCountryFetchesRow struct {
	TopicID       int64
	Country       string
	LastFetchedAt time.Time
}

// When a successful call last covered each topic for each country.
func (q *Queries) ListCountryFetches(ctx context.Context) ([]ListCountryFetchesRow, error) {
	rows, err := q.db.Query(ctx, listCountryFetches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountryFetchesRow{}
	for rows.Next() {
		var i ListCountryFetchesRow
		if err := rows.Scan(&i.TopicID, &i.Country, &i.LastFetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFetchTopics = `-- name: ListFetchTopics :many
SELECT t.id,
    t.slug,
    t.name,
    t.description,
    p.slug AS parent_slug,
    COALESCE(tp.priority, $1::integer)::integer AS priority,
    COALESCE((SELECT sum(s.followers) FROM topic_stats s WHERE s.topic_id = t.id), 0)::integer AS followers,
    COALESCE((SELECT sum(s.profession_users) FROM topic_stats s WHERE s.topic_id = t.id), 0)::integer AS profession_users,
    COALESCE((SELECT sum(s.engaged_7d) FROM topic_stats s WHERE s.topic_id = t.id), 0)::integer AS engaged_7d,
    COALESCE((SELECT sum(s.views_7d) FROM topic_stats s WHERE s.topic_id = t.id), 0)::integer AS views_7d,
    EXISTS (SELECT 1 FROM topics c WHERE c.parent_id = t.id) AS has_children,
    COALESCE((SELECT array_agg(h.url ORDER BY h.url) FROM topic_hints h WHERE h.topic_id = t.id), '{}')::text[] AS hints,
    COALESCE((
        SELECT array_agg(pr.name ORDER BY pr.position, pr.name)
        FROM profession_topics pt JOIN professions pr ON pr.id = pt.profession_id
        WHERE pt.topic_id = COALESCE(t.parent_id, t.id)
    ), '{}')::text[] AS professions,
    EXISTS (
        SELECT 1 FROM profession_topics pt JOIN professions pr ON pr.id = pt.profession_id
        WHERE pt.topic_id = COALESCE(t.parent_id, t.id) AND pr.launched
    ) AS launched,
    (t.headline OR COALESCE(p.headline, false))::boolean AS headline,
    -- 'epoch' when no call covering the topic has succeeded yet.
    COALESCE((
        SELECT max(fr.started_at) FROM fetch_runs fr
        WHERE fr.status = 'succeeded' AND fr.country IS NULL AND fr.topic_ids @> ARRAY[t.id]
    ), 'epoch')::timestamptz AS last_fetched_at
FROM topics t
LEFT JOIN topics p ON p.id = t.parent_id
LEFT JOIN topic_priority tp ON tp.topic_id = t.id
ORDER BY t.slug
`

type ListFetchTopicsRow struct {
	ID              int64
	Slug            string
	Name            string
	Description     string
	ParentSlug      *string
	Priority        int32
	Followers       int32
	ProfessionUsers int32
	Engaged7d       int32
	Views7d         int32
	HasChildren     bool
	Hints           []string
	Professions     []string
	Launched        bool
	Headline        bool
	LastFetchedAt   time.Time
}

// Every topic with what fetch planning needs: its parent, priority (@default_priority when it has
// none), hints, demand (summed over the hosted envs), the professions its root serves, whether one
// of them is launched, whether it or its parent is a headline, whether it has children and when a
// fetch call covering it last succeeded.
func (q *Queries) ListFetchTopics(ctx context.Context, defaultPriority int32) ([]ListFetchTopicsRow, error) {
	rows, err := q.db.Query(ctx, listFetchTopics, defaultPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFetchTopicsRow{}
	for rows.Next() {
		var i ListFetchTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ParentSlug,
			&i.Priority,
			&i.Followers,
			&i.ProfessionUsers,
			&i.Engaged7d,
			&i.Views7d,
			&i.HasChildren,
			&i.Hints,
			&i.Professions,
			&i.Launched,
			&i.Headline,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentStoryRefs = `-- name: ListRecentStoryRefs :many
SELECT s.title, COALESCE(MIN(ss.url), '')::text AS url
FROM stories s
LEFT JOIN story_sources ss ON ss.story_id = s.id
WHERE s.published_at >= $1
    AND ($2::text = '' OR $2::text = ANY(s.countries))
    AND EXISTS (SELECT 1 FROM story_topics st WHERE st.story_id = s.id AND st.topic_id = ANY($3::bigint[]))
GROUP BY s.id
ORDER BY s.published_at DESC, s.id DESC
LIMIT $4
`

type ListRecentStoryRefsParams struct {
	Since    time.Time
	Country  string
	TopicIds []int64
	MaxRows  int32
}

type ListRecentStoryRefsRow struct {
	Title string
	Url   string
}

// Recent stories in the given topics, sent to Claude so it skips what we already have. A
// non-empty @country keeps only stories for that country.
func (q *Queries) ListRecentStoryRefs(ctx context.Context, arg ListRecentStoryRefsParams) ([]ListRecentStoryRefsRow, error) {
	rows, err := q.db.Query(ctx, listRecentStoryRefs,
		arg.Since,
		arg.Country,
		arg.TopicIds,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentStoryRefsRow{}
	for rows.Next() {
		var i ListRecentStoryRefsRow
		if err := rows.Scan(&i.Title, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicRelations = `-- name: ListTopicRelations :many
SELECT a.slug AS slug, b.slug AS related_slug
FROM topic_relations r
JOIN topics a ON a.id = r.topic_id
JOIN topics b ON b.id = r.related_id
UNION ALL
SELECT b.slug, a.slug
FROM topic_relations r
JOIN topics a ON a.id = r.topic_id
JOIN topics b ON b.id = r.related_id
`

type ListTopicRelationsRow struct {
	Slug        string
	RelatedSlug string
}

// Both directions of every related pair.
func (q *Queries) ListTopicRelations(ctx context.Context) ([]ListTopicRelationsRow, error) {
	rows, err := q.db.Query(ctx, listTopicRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicRelationsRow{}
	for rows.Next() {
		var i ListTopicRelationsRow
		if err := rows.Scan(&i.Slug, &i.RelatedSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startFetchRun = `-- name: StartFetchRun :one
INSERT INTO fetch_runs (group_slug, topic_ids, country)
VALUES ($1, $2::bigint[], $3)
RETURNING id
`

type StartFetchRunParams struct {
	GroupSlug string
	TopicIds  []int64
	Country   *string
}

func (q *Queries) StartFetchRun(ctx context.Context, arg StartFetchRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, startFetchRun, arg.GroupSlug, arg.TopicIds, arg.Country)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const touchMergedStory = `-- name: TouchMergedStory :exec
UPDATE stories
SET importance = GREATEST(importance, $1::smallint),
    updated_at = now()
WHERE id = $2
`

type TouchMergedStoryParams struct {
	Importance int16
	ID         int64
}

// A merged item raises the story's importance and marks it for the next sync.
func (q *Queries) TouchMergedStory(ctx context.Context, arg TouchMergedStoryParams) error {
	_, err := q.db.Exec(ctx, touchMergedStory, arg.Importance, arg.ID)
	return err
}
