// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CountryStat struct {
	Env     string
	Country string
	Users   int32
}

type DeviceToken struct {
	Token     string
	UserID    int64
	Platform  string
	UpdatedAt time.Time
}

type FetchRun struct {
	ID           int64
	GroupSlug    string
	StartedAt    time.Time
	FinishedAt   *time.Time
	Status       string
	StoriesAdded int32
	Error        *string
	CostUsd      *float64
	TopicIds     []int64
	Country      *string
}

type Profession struct {
	ID          int64
	Slug        string
	Name        string
	Description string
	Position    int16
	UpdatedAt   time.Time
}

type ProfessionTopic struct {
	ProfessionID int64
	TopicID      int64
	Position     int16
}

type RequestInbox struct {
	ID         int64
	Env        string
	RemoteID   int64
	Text       string
	CreatedAt  time.Time
	Status     string
	TopicSlug  *string
	Note       *string
	ResolvedAt *time.Time
	PushedAt   *time.Time
}

type Story struct {
	ID            int64
	Title         string
	Summary       string
	BodyMd        string
	Kind          string
	Severity      *string
	Importance    int16
	PublishedAt   time.Time
	DedupeKeys    []byte
	Model         string
	PromptVersion string
	CreatedAt     time.Time
	Search        interface{}
	NotifiedAt    *time.Time
	Uid           pgtype.UUID
	UpdatedAt     time.Time
	Countries     []string
}

type StorySource struct {
	StoryID    int64
	Url        string
	SourceName string
}

type StoryTombstone struct {
	Uid           pgtype.UUID
	MergedIntoUid pgtype.UUID
	DeletedAt     time.Time
}

type StoryTopic struct {
	StoryID int64
	TopicID int64
}

type StoryView struct {
	UserID  int64
	StoryID int64
	SeenAt  time.Time
}

type SyncState struct {
	Key   string
	Value time.Time
}

type TombstonePush struct {
	Uid      pgtype.UUID
	Env      string
	PushedAt time.Time
}

type Topic struct {
	ID          int64
	Slug        string
	Name        string
	ParentID    *int64
	Description string
	UpdatedAt   time.Time
}

type TopicHint struct {
	TopicID int64
	Url     string
}

type TopicPriority struct {
	TopicID  int64
	Priority int16
}

type TopicRelation struct {
	TopicID   int64
	RelatedID int64
}

type TopicRequest struct {
	ID         int64
	UserID     int64
	Text       string
	Status     string
	TopicID    *int64
	Note       *string
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

type TopicStat struct {
	TopicID         int64
	Env             string
	Followers       int32
	UpdatedAt       time.Time
	ProfessionUsers int32
	Views7d         int32
}

type User struct {
	ID          int64
	FirebaseUid string
	Email       *string
	CreatedAt   time.Time
	Country     *string
}

type UserBookmark struct {
	UserID    int64
	StoryID   int64
	CreatedAt time.Time
}

type UserProfession struct {
	UserID       int64
	ProfessionID int64
}

type UserStoryState struct {
	UserID  int64
	StoryID int64
	ReadAt  time.Time
}

type UserTopic struct {
	UserID  int64
	TopicID int64
}
