// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
	"time"
)

const addCountryStat = `-- name: AddCountryStat :exec
INSERT INTO country_stats (env, country, users) VALUES ($1, $2, $3)
`

type AddCountryStatParams struct {
	Env     string
	Country string
	Users   int32
}

func (q *Queries) AddCountryStat(ctx context.Context, arg AddCountryStatParams) error {
	_, err := q.db.Exec(ctx, addCountryStat, arg.Env, arg.Country, arg.Users)
	return err
}

const addTopicStat = `-- name: AddTopicStat :execrows
INSERT INTO topic_stats (topic_id, env, followers, profession_users, engaged_7d, views_7d)
SELECT id, $1, $2, $3, $4, $5 FROM topics WHERE slug = $6
`

type AddTopicStatParams struct {
	Env             string
	Followers       int32
	ProfessionUsers int32
	Engaged7d       int32
	Views7d         int32
	Slug            string
}

// Zero rows when the hosted topic is not in the local catalog.
func (q *Queries) AddTopicStat(ctx context.Context, arg AddTopicStatParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTopicStat,
		arg.Env,
		arg.Followers,
		arg.ProfessionUsers,
		arg.Engaged7d,
		arg.Views7d,
		arg.Slug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCountryStats = `-- name: DeleteCountryStats :exec
DELETE FROM country_stats WHERE env = $1
`

func (q *Queries) DeleteCountryStats(ctx context.Context, env string) error {
	_, err := q.db.Exec(ctx, deleteCountryStats, env)
	return err
}

const deleteTopicStats = `-- name: DeleteTopicStats :exec
DELETE FROM topic_stats WHERE env = $1
`

func (q *Queries) DeleteTopicStats(ctx context.Context, env string) error {
	_, err := q.db.Exec(ctx, deleteTopicStats, env)
	return err
}

const listHostedCountryDemand = `-- name: ListHostedCountryDemand :many
SELECT country::text AS country, count(*)::integer AS users
FROM users
WHERE country IS NOT NULL
GROUP BY country
`

type ListHostedCountryDemandRow struct {
	Country string
	Users   int32
}

// Run against the hosted DB. Users per chosen country: aggregate only, never per user.
func (q *Queries) ListHostedCountryDemand(ctx context.Context) ([]ListHostedCountryDemandRow, error) {
	rows, err := q.db.Query(ctx, listHostedCountryDemand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostedCountryDemandRow{}
	for rows.Next() {
		var i ListHostedCountryDemandRow
		if err := rows.Scan(&i.Country, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostedPendingRequests = `-- name: ListHostedPendingRequests :many
SELECT id, text, created_at
FROM topic_requests
WHERE status = 'pending'
ORDER BY id
`

type ListHostedPendingRequestsRow struct {
	ID        int64
	Text      string
	CreatedAt time.Time
}

// Run against the hosted DB. Only the request itself is read, never the user.
func (q *Queries) ListHostedPendingRequests(ctx context.Context) ([]ListHostedPendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listHostedPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostedPendingRequestsRow{}
	for rows.Next() {
		var i ListHostedPendingRequestsRow
		if err := rows.Scan(&i.ID, &i.Text, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostedTopicDemand = `-- name: ListHostedTopicDemand :many
SELECT d.slug, d.followers, d.profession_users, d.engaged, d.views
FROM (
    SELECT t.slug,
        (SELECT count(*) FROM user_topics ut WHERE ut.topic_id = t.id)::integer AS followers,
        (SELECT count(DISTINCT up.user_id)
            FROM profession_topics pt
            JOIN user_professions up ON up.profession_id = pt.profession_id
            WHERE pt.topic_id = COALESCE(t.parent_id, t.id)
                AND NOT EXISTS (
                    SELECT 1 FROM user_topic_mutes um
                    WHERE um.user_id = up.user_id AND um.topic_id IN (t.id, t.parent_id)
                ))::integer AS profession_users,
        (SELECT count(DISTINCT e.user_id)
            FROM story_topics st
            JOIN (
                SELECT r.user_id, r.story_id FROM user_story_state r WHERE r.read_at >= $1
                UNION ALL
                SELECT b.user_id, b.story_id FROM user_bookmarks b WHERE b.created_at >= $1
            ) e ON e.story_id = st.story_id
            WHERE st.topic_id = t.id
                AND NOT EXISTS (
                    SELECT 1 FROM user_topic_mutes um
                    WHERE um.user_id = e.user_id AND um.topic_id IN (t.id, t.parent_id)
                ))::integer AS engaged,
        (SELECT count(DISTINCT v.user_id)
            FROM story_topics st
            JOIN story_views v ON v.story_id = st.story_id
            WHERE st.topic_id = t.id AND v.seen_at >= $1
                AND NOT EXISTS (
                    SELECT 1 FROM user_topic_mutes um
                    WHERE um.user_id = v.user_id AND um.topic_id IN (t.id, t.parent_id)
                ))::integer AS views
    FROM topics t
) d
WHERE d.followers > 0 OR d.profession_users > 0 OR d.engaged > 0 OR d.views > 0
`

type ListHostedTopicDemandRow struct {
	Slug            string
	Followers       int32
	ProfessionUsers int32
	Engaged         int32
	Views           int32
}

// Run against the hosted DB. Aggregate demand per topic slug, never per user: followers, users whose
// profession maps to the topic's root, distinct users who opened (read) or saved one of the topic's
// stories since @since, and distinct viewers of its stories since @since. Users who muted the topic
// or its root don't count. Topics with no demand are left out.
func (q *Queries) ListHostedTopicDemand(ctx context.Context, since time.Time) ([]ListHostedTopicDemandRow, error) {
	rows, err := q.db.Query(ctx, listHostedTopicDemand, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostedTopicDemandRow{}
	for rows.Next() {
		var i ListHostedTopicDemandRow
		if err := rows.Scan(
			&i.Slug,
			&i.Followers,
			&i.ProfessionUsers,
			&i.Engaged,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInbox = `-- name: ListPendingInbox :many
SELECT id, env, text, created_at
FROM request_inbox
WHERE status = 'pending'
ORDER BY created_at, id
`

type ListPendingInboxRow struct {
	ID        int64
	Env       string
	Text      string
	CreatedAt time.Time
}

func (q *Queries) ListPendingInbox(ctx context.Context) ([]ListPendingInboxRow, error) {
	rows, err := q.db.Query(ctx, listPendingInbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInboxRow{}
	for rows.Next() {
		var i ListPendingInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Env,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHostedStories = `-- name: PruneHostedStories :execrows
DELETE FROM stories
WHERE id IN (
    SELECT s.id FROM stories s
    WHERE NOT EXISTS (SELECT 1 FROM user_bookmarks b WHERE b.story_id = s.id)
        AND s.published_at < $1
    ORDER BY s.id
    LIMIT $2
)
`

type PruneHostedStoriesParams struct {
	MaxAgeBefore time.Time
	MaxRows      int32
}

// Run against the hosted DB. Deletes at most @max_rows stories that nobody saved and that were
// published before @max_age_before. Sources, topics, views and read state cascade.
func (q *Queries) PruneHostedStories(ctx context.Context, arg PruneHostedStoriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneHostedStories, arg.MaxAgeBefore, arg.MaxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveInboxRequest = `-- name: ResolveInboxRequest :execrows
UPDATE request_inbox
SET status = $1, topic_slug = $2, note = $3, resolved_at = now()
WHERE id = $4 AND status = 'pending'
`

type ResolveInboxRequestParams struct {
	Status    string
	TopicSlug *string
	Note      *string
	ID        int64
}

func (q *Queries) ResolveInboxRequest(ctx context.Context, arg ResolveInboxRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveInboxRequest,
		arg.Status,
		arg.TopicSlug,
		arg.Note,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInboxRequest = `-- name: UpsertInboxRequest :execrows
INSERT INTO request_inbox (env, remote_id, text, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (env, remote_id) DO NOTHING
`

type UpsertInboxRequestParams struct {
	Env       string
	RemoteID  int64
	Text      string
	CreatedAt time.Time
}

// A request already in the inbox keeps its local decision.
func (q *Queries) UpsertInboxRequest(ctx context.Context, arg UpsertInboxRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertInboxRequest,
		arg.Env,
		arg.RemoteID,
		arg.Text,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
