// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
	"time"
)

const addTopicStat = `-- name: AddTopicStat :execrows
INSERT INTO topic_stats (topic_id, env, followers)
SELECT id, $1, $2 FROM topics WHERE slug = $3
`

type AddTopicStatParams struct {
	Env       string
	Followers int32
	Slug      string
}

// Zero rows when the hosted topic is not in the local catalog.
func (q *Queries) AddTopicStat(ctx context.Context, arg AddTopicStatParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTopicStat, arg.Env, arg.Followers, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTopicStats = `-- name: DeleteTopicStats :exec
DELETE FROM topic_stats WHERE env = $1
`

func (q *Queries) DeleteTopicStats(ctx context.Context, env string) error {
	_, err := q.db.Exec(ctx, deleteTopicStats, env)
	return err
}

const listHostedFollowerCounts = `-- name: ListHostedFollowerCounts :many
SELECT t.slug, count(*)::integer AS followers
FROM user_topics ut
JOIN topics t ON t.id = ut.topic_id
GROUP BY t.slug
`

type ListHostedFollowerCountsRow struct {
	Slug      string
	Followers int32
}

// Run against the hosted DB. Aggregate follower counts per topic slug.
func (q *Queries) ListHostedFollowerCounts(ctx context.Context) ([]ListHostedFollowerCountsRow, error) {
	rows, err := q.db.Query(ctx, listHostedFollowerCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostedFollowerCountsRow{}
	for rows.Next() {
		var i ListHostedFollowerCountsRow
		if err := rows.Scan(&i.Slug, &i.Followers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostedPendingRequests = `-- name: ListHostedPendingRequests :many
SELECT id, text, created_at
FROM topic_requests
WHERE status = 'pending'
ORDER BY id
`

type ListHostedPendingRequestsRow struct {
	ID        int64
	Text      string
	CreatedAt time.Time
}

// Run against the hosted DB. Only the request itself is read, never the user.
func (q *Queries) ListHostedPendingRequests(ctx context.Context) ([]ListHostedPendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listHostedPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostedPendingRequestsRow{}
	for rows.Next() {
		var i ListHostedPendingRequestsRow
		if err := rows.Scan(&i.ID, &i.Text, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInbox = `-- name: ListPendingInbox :many
SELECT id, env, text, created_at
FROM request_inbox
WHERE status = 'pending'
ORDER BY created_at, id
`

type ListPendingInboxRow struct {
	ID        int64
	Env       string
	Text      string
	CreatedAt time.Time
}

func (q *Queries) ListPendingInbox(ctx context.Context) ([]ListPendingInboxRow, error) {
	rows, err := q.db.Query(ctx, listPendingInbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInboxRow{}
	for rows.Next() {
		var i ListPendingInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Env,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInboxRequest = `-- name: ResolveInboxRequest :execrows
UPDATE request_inbox
SET status = $1, topic_slug = $2, note = $3, resolved_at = now()
WHERE id = $4 AND status = 'pending'
`

type ResolveInboxRequestParams struct {
	Status    string
	TopicSlug *string
	Note      *string
	ID        int64
}

func (q *Queries) ResolveInboxRequest(ctx context.Context, arg ResolveInboxRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveInboxRequest,
		arg.Status,
		arg.TopicSlug,
		arg.Note,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInboxRequest = `-- name: UpsertInboxRequest :execrows
INSERT INTO request_inbox (env, remote_id, text, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (env, remote_id) DO NOTHING
`

type UpsertInboxRequestParams struct {
	Env       string
	RemoteID  int64
	Text      string
	CreatedAt time.Time
}

// A request already in the inbox keeps its local decision.
func (q *Queries) UpsertInboxRequest(ctx context.Context, arg UpsertInboxRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertInboxRequest,
		arg.Env,
		arg.RemoteID,
		arg.Text,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
