// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package db

import (
	"context"
)

const addTopicHint = `-- name: AddTopicHint :execrows
INSERT INTO topic_hints (topic_id, url)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTopicHintParams struct {
	TopicID int64
	Url     string
}

func (q *Queries) AddTopicHint(ctx context.Context, arg AddTopicHintParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTopicHint, arg.TopicID, arg.Url)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addTopicRelation = `-- name: AddTopicRelation :execrows
INSERT INTO topic_relations (topic_id, related_id)
VALUES (LEAST($1::bigint, $2::bigint), GREATEST($1::bigint, $2::bigint))
ON CONFLICT DO NOTHING
`

type AddTopicRelationParams struct {
	A int64
	B int64
}

// Relations are symmetric and stored once, smaller id first.
func (q *Queries) AddTopicRelation(ctx context.Context, arg AddTopicRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTopicRelation, arg.A, arg.B)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTopicHeadline = `-- name: SetTopicHeadline :exec
UPDATE topics SET headline = $1 WHERE id = $2 AND headline IS DISTINCT FROM $1
`

type SetTopicHeadlineParams struct {
	Headline bool
	ID       int64
}

func (q *Queries) SetTopicHeadline(ctx context.Context, arg SetTopicHeadlineParams) error {
	_, err := q.db.Exec(ctx, setTopicHeadline, arg.Headline, arg.ID)
	return err
}

const setTopicPriority = `-- name: SetTopicPriority :exec
INSERT INTO topic_priority (topic_id, priority)
VALUES ($1, $2)
ON CONFLICT (topic_id) DO UPDATE SET priority = EXCLUDED.priority
`

type SetTopicPriorityParams struct {
	TopicID  int64
	Priority int16
}

func (q *Queries) SetTopicPriority(ctx context.Context, arg SetTopicPriorityParams) error {
	_, err := q.db.Exec(ctx, setTopicPriority, arg.TopicID, arg.Priority)
	return err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (slug, name, parent_id, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
SET name        = EXCLUDED.name,
    parent_id   = EXCLUDED.parent_id,
    description = EXCLUDED.description,
    updated_at  = CASE
        WHEN (topics.name, topics.parent_id, topics.description)
            IS DISTINCT FROM (EXCLUDED.name, EXCLUDED.parent_id, EXCLUDED.description)
        THEN now()
        ELSE topics.updated_at
    END
RETURNING id
`

type UpsertTopicParams struct {
	Slug        string
	Name        string
	ParentID    *int64
	Description string
}

// updated_at only moves when a field actually changes.
func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTopic,
		arg.Slug,
		arg.Name,
		arg.ParentID,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
