// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"
	"time"
)

const addStorySource = `-- name: AddStorySource :exec
INSERT INTO story_sources (story_id, raw_item_id, url, source_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (story_id, url) DO NOTHING
`

type AddStorySourceParams struct {
	StoryID    int64
	RawItemID  *int64
	Url        string
	SourceName string
}

func (q *Queries) AddStorySource(ctx context.Context, arg AddStorySourceParams) error {
	_, err := q.db.Exec(ctx, addStorySource,
		arg.StoryID,
		arg.RawItemID,
		arg.Url,
		arg.SourceName,
	)
	return err
}

const addStoryTopics = `-- name: AddStoryTopics :exec
INSERT INTO story_topics (story_id, topic_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddStoryTopicsParams struct {
	StoryID  int64
	TopicIds []int64
}

func (q *Queries) AddStoryTopics(ctx context.Context, arg AddStoryTopicsParams) error {
	_, err := q.db.Exec(ctx, addStoryTopics, arg.StoryID, arg.TopicIds)
	return err
}

const claimPendingRawItems = `-- name: ClaimPendingRawItems :many
SELECT ri.id, ri.url, ri.title, ri.content, ri.published_at, s.name AS source_name
FROM raw_items ri
JOIN sources s ON s.id = ri.source_id
WHERE ri.status = 'pending'
ORDER BY ri.published_at DESC NULLS LAST, ri.id DESC
LIMIT $1
FOR UPDATE OF ri SKIP LOCKED
`

type ClaimPendingRawItemsRow struct {
	ID          int64
	Url         string
	Title       string
	Content     *string
	PublishedAt *time.Time
	SourceName  string
}

// Newest first, so a tight budget is spent on fresh items. Locks the rows until commit.
func (q *Queries) ClaimPendingRawItems(ctx context.Context, maxItems int32) ([]ClaimPendingRawItemsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingRawItems, maxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingRawItemsRow{}
	for rows.Next() {
		var i ClaimPendingRawItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMergeTarget = `-- name: FindMergeTarget :one
SELECT id FROM stories
WHERE published_at >= $1
    AND (
        EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(dedupe_keys -> 'cve_ids') c
            WHERE c = ANY($2::text[])
        )
        OR (
            $3::text <> '' AND $4::text <> ''
            AND dedupe_keys ->> 'project' = $3::text
            AND dedupe_keys ->> 'version' = $4::text
        )
    )
ORDER BY published_at DESC, id DESC
LIMIT 1
`

type FindMergeTargetParams struct {
	Since   time.Time
	CveIds  []string
	Project string
	Version string
}

// A recent story about the same CVE, or the same project and version.
func (q *Queries) FindMergeTarget(ctx context.Context, arg FindMergeTargetParams) (int64, error) {
	row := q.db.QueryRow(ctx, findMergeTarget,
		arg.Since,
		arg.CveIds,
		arg.Project,
		arg.Version,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishAIBatch = `-- name: FinishAIBatch :exec
UPDATE ai_batches
SET status = $1,
    input_tokens = $2,
    output_tokens = $3,
    cache_read_tokens = $4,
    cache_creation_tokens = $5,
    ended_at = now()
WHERE id = $6
`

type FinishAIBatchParams struct {
	Status              string
	InputTokens         int64
	OutputTokens        int64
	CacheReadTokens     int64
	CacheCreationTokens int64
	ID                  int64
}

func (q *Queries) FinishAIBatch(ctx context.Context, arg FinishAIBatchParams) error {
	_, err := q.db.Exec(ctx, finishAIBatch,
		arg.Status,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheCreationTokens,
		arg.ID,
	)
	return err
}

const getRawItem = `-- name: GetRawItem :one
SELECT ri.id, ri.url, ri.title, ri.content, ri.published_at, ri.fetched_at, ri.status, s.name AS source_name
FROM raw_items ri
JOIN sources s ON s.id = ri.source_id
WHERE ri.id = $1
`

type GetRawItemRow struct {
	ID          int64
	Url         string
	Title       string
	Content     *string
	PublishedAt *time.Time
	FetchedAt   time.Time
	Status      string
	SourceName  string
}

func (q *Queries) GetRawItem(ctx context.Context, id int64) (GetRawItemRow, error) {
	row := q.db.QueryRow(ctx, getRawItem, id)
	var i GetRawItemRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Status,
		&i.SourceName,
	)
	return i, err
}

const insertAIBatch = `-- name: InsertAIBatch :one
INSERT INTO ai_batches (anthropic_batch_id, status, item_count, estimated_tokens)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertAIBatchParams struct {
	AnthropicBatchID string
	Status           string
	ItemCount        int32
	EstimatedTokens  int64
}

func (q *Queries) InsertAIBatch(ctx context.Context, arg InsertAIBatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAIBatch,
		arg.AnthropicBatchID,
		arg.Status,
		arg.ItemCount,
		arg.EstimatedTokens,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStory = `-- name: InsertStory :one
INSERT INTO stories (title, summary, body_md, kind, severity, importance, published_at, dedupe_keys, model, prompt_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertStoryParams struct {
	Title         string
	Summary       string
	BodyMd        string
	Kind          string
	Severity      *string
	Importance    int16
	PublishedAt   time.Time
	DedupeKeys    []byte
	Model         string
	PromptVersion string
}

func (q *Queries) InsertStory(ctx context.Context, arg InsertStoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStory,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.Kind,
		arg.Severity,
		arg.Importance,
		arg.PublishedAt,
		arg.DedupeKeys,
		arg.Model,
		arg.PromptVersion,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOpenAIBatches = `-- name: ListOpenAIBatches :many
SELECT id, anthropic_batch_id FROM ai_batches WHERE ended_at IS NULL ORDER BY id
`

type ListOpenAIBatchesRow struct {
	ID               int64
	AnthropicBatchID string
}

func (q *Queries) ListOpenAIBatches(ctx context.Context) ([]ListOpenAIBatchesRow, error) {
	rows, err := q.db.Query(ctx, listOpenAIBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenAIBatchesRow{}
	for rows.Next() {
		var i ListOpenAIBatchesRow
		if err := rows.Scan(&i.ID, &i.AnthropicBatchID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedRawItems = `-- name: ListSubmittedRawItems :many
SELECT ri.id, ri.url, ri.published_at, ri.fetched_at, s.name AS source_name
FROM raw_items ri
JOIN sources s ON s.id = ri.source_id
WHERE ri.ai_batch_id = $1 AND ri.status = 'submitted'
`

type ListSubmittedRawItemsRow struct {
	ID          int64
	Url         string
	PublishedAt *time.Time
	FetchedAt   time.Time
	SourceName  string
}

func (q *Queries) ListSubmittedRawItems(ctx context.Context, batchID *int64) ([]ListSubmittedRawItemsRow, error) {
	rows, err := q.db.Query(ctx, listSubmittedRawItems, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmittedRawItemsRow{}
	for rows.Next() {
		var i ListSubmittedRawItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawItemsSubmitted = `-- name: MarkRawItemsSubmitted :exec
UPDATE raw_items SET status = 'submitted', ai_batch_id = $1 WHERE id = ANY($2::bigint[])
`

type MarkRawItemsSubmittedParams struct {
	BatchID *int64
	Ids     []int64
}

func (q *Queries) MarkRawItemsSubmitted(ctx context.Context, arg MarkRawItemsSubmittedParams) error {
	_, err := q.db.Exec(ctx, markRawItemsSubmitted, arg.BatchID, arg.Ids)
	return err
}

const raiseStoryImportance = `-- name: RaiseStoryImportance :exec
UPDATE stories SET importance = GREATEST(importance, $1::smallint) WHERE id = $2
`

type RaiseStoryImportanceParams struct {
	Importance int16
	ID         int64
}

func (q *Queries) RaiseStoryImportance(ctx context.Context, arg RaiseStoryImportanceParams) error {
	_, err := q.db.Exec(ctx, raiseStoryImportance, arg.Importance, arg.ID)
	return err
}

const retryRawItem = `-- name: RetryRawItem :one
UPDATE raw_items
SET attempts = attempts + 1,
    error = $1,
    ai_batch_id = NULL,
    status = CASE WHEN attempts + 1 >= $2::smallint THEN 'failed' ELSE 'pending' END
WHERE id = $3
RETURNING status
`

type RetryRawItemParams struct {
	Error       *string
	MaxAttempts int16
	ID          int64
}

// Counts a failed attempt: back to pending, or failed once max_attempts is reached.
func (q *Queries) RetryRawItem(ctx context.Context, arg RetryRawItemParams) (string, error) {
	row := q.db.QueryRow(ctx, retryRawItem, arg.Error, arg.MaxAttempts, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const setRawItemStatus = `-- name: SetRawItemStatus :exec
UPDATE raw_items SET status = $1, error = $2, ai_batch_id = NULL WHERE id = $3
`

type SetRawItemStatusParams struct {
	Status string
	Error  *string
	ID     int64
}

func (q *Queries) SetRawItemStatus(ctx context.Context, arg SetRawItemStatusParams) error {
	_, err := q.db.Exec(ctx, setRawItemStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const tokensUsedSince = `-- name: TokensUsedSince :one
SELECT COALESCE(SUM(
    CASE WHEN ended_at IS NULL THEN estimated_tokens
         ELSE input_tokens + output_tokens + cache_read_tokens + cache_creation_tokens END
), 0)::bigint
FROM ai_batches
WHERE submitted_at >= $1
`

// Actual usage for finished batches, the submit-time estimate for batches still running.
func (q *Queries) TokensUsedSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, tokensUsedSince, since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAIBatchStatus = `-- name: UpdateAIBatchStatus :exec
UPDATE ai_batches SET status = $1 WHERE id = $2
`

type UpdateAIBatchStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateAIBatchStatus(ctx context.Context, arg UpdateAIBatchStatusParams) error {
	_, err := q.db.Exec(ctx, updateAIBatchStatus, arg.Status, arg.ID)
	return err
}
