// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"time"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string
	UserID int64
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	return err
}

const deleteDeviceTokens = `-- name: DeleteDeviceTokens :exec
DELETE FROM device_tokens WHERE token = ANY($1::text[])
`

func (q *Queries) DeleteDeviceTokens(ctx context.Context, tokens []string) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokens, tokens)
	return err
}

const listDeviceTokensForStory = `-- name: ListDeviceTokensForStory :many
WITH RECURSIVE story_scope AS (
    SELECT st.topic_id AS id FROM story_topics st WHERE st.story_id = $1
    UNION
    SELECT t.parent_id FROM topics t JOIN story_scope s ON t.id = s.id WHERE t.parent_id IS NOT NULL
)
SELECT DISTINCT dt.token
FROM device_tokens dt
JOIN user_topics ut ON ut.user_id = dt.user_id
WHERE ut.topic_id IN (SELECT id FROM story_scope)
`

// Device tokens of users who follow a topic of the story or an ancestor of one.
func (q *Queries) ListDeviceTokensForStory(ctx context.Context, storyID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForStory, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoriesToNotify = `-- name: ListStoriesToNotify :many
SELECT id, title, summary FROM stories
WHERE notified_at IS NULL
    AND kind = 'security' AND severity IN ('high', 'critical')
    AND created_at >= $1
ORDER BY id
`

type ListStoriesToNotifyRow struct {
	ID      int64
	Title   string
	Summary string
}

// Recent high-severity security stories that have not been pushed yet.
func (q *Queries) ListStoriesToNotify(ctx context.Context, since time.Time) ([]ListStoriesToNotifyRow, error) {
	rows, err := q.db.Query(ctx, listStoriesToNotify, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoriesToNotifyRow{}
	for rows.Next() {
		var i ListStoriesToNotifyRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoryNotified = `-- name: MarkStoryNotified :exec
UPDATE stories SET notified_at = now() WHERE id = $1
`

func (q *Queries) MarkStoryNotified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markStoryNotified, id)
	return err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (token, user_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform, updated_at = now()
`

type UpsertDeviceTokenParams struct {
	Token    string
	UserID   int64
	Platform string
}

// A token belongs to one user: signing in as someone else on the same device moves it.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, arg.Token, arg.UserID, arg.Platform)
	return err
}
