// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiBatch struct {
	ID                  int64
	AnthropicBatchID    string
	Status              string
	ItemCount           int32
	InputTokens         int64
	OutputTokens        int64
	CacheReadTokens     int64
	CacheCreationTokens int64
	SubmittedAt         time.Time
	EndedAt             *time.Time
	EstimatedTokens     int64
}

type DeviceToken struct {
	Token     string
	UserID    int64
	Platform  string
	UpdatedAt time.Time
}

type RawItem struct {
	ID          int64
	SourceID    int64
	ExternalID  *string
	Url         string
	UrlHash     []byte
	Title       string
	Content     *string
	PublishedAt *time.Time
	Status      string
	Error       *string
	FetchedAt   time.Time
	Attempts    int16
	AiBatchID   *int64
}

type Source struct {
	ID              int64
	Name            string
	Kind            string
	Config          []byte
	DefaultTopicIds []int64
	PollInterval    pgtype.Interval
	Etag            *string
	LastModified    *string
	LastPolledAt    *time.Time
	Enabled         bool
}

type Story struct {
	ID              int64
	Title           string
	Summary         string
	BodyMd          string
	Kind            string
	Severity        *string
	Importance      int16
	PublishedAt     time.Time
	DedupeKeys      []byte
	Model           string
	PromptVersion   string
	CreatedAt       time.Time
	Search          interface{}
	NotifiedAt      *time.Time
	DedupeCheckedAt *time.Time
}

type StorySource struct {
	StoryID    int64
	RawItemID  *int64
	Url        string
	SourceName string
}

type StoryTopic struct {
	StoryID int64
	TopicID int64
}

type Topic struct {
	ID          int64
	Slug        string
	Name        string
	ParentID    *int64
	Description string
}

type User struct {
	ID          int64
	FirebaseUid string
	Email       *string
	CreatedAt   time.Time
}

type UserBookmark struct {
	UserID    int64
	StoryID   int64
	CreatedAt time.Time
}

type UserStoryState struct {
	UserID  int64
	StoryID int64
	ReadAt  time.Time
}

type UserTopic struct {
	UserID  int64
	TopicID int64
}
