// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"time"
)

const existingURLHashes = `-- name: ExistingURLHashes :many
SELECT url_hash FROM raw_items WHERE url_hash = ANY($1::bytea[])
`

func (q *Queries) ExistingURLHashes(ctx context.Context, hashes [][]byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, existingURLHashes, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var url_hash []byte
		if err := rows.Scan(&url_hash); err != nil {
			return nil, err
		}
		items = append(items, url_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSource = `-- name: GetSource :one
SELECT id, name, kind, config, etag, last_modified, enabled
FROM sources
WHERE id = $1
`

type GetSourceRow struct {
	ID           int64
	Name         string
	Kind         string
	Config       []byte
	Etag         *string
	LastModified *string
	Enabled      bool
}

func (q *Queries) GetSource(ctx context.Context, id int64) (GetSourceRow, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i GetSourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Etag,
		&i.LastModified,
		&i.Enabled,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, kind, config, etag, last_modified, enabled
FROM sources
WHERE name = $1
`

type GetSourceByNameRow struct {
	ID           int64
	Name         string
	Kind         string
	Config       []byte
	Etag         *string
	LastModified *string
	Enabled      bool
}

func (q *Queries) GetSourceByName(ctx context.Context, name string) (GetSourceByNameRow, error) {
	row := q.db.QueryRow(ctx, getSourceByName, name)
	var i GetSourceByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Etag,
		&i.LastModified,
		&i.Enabled,
	)
	return i, err
}

const getSourceLastPolledAt = `-- name: GetSourceLastPolledAt :one
SELECT last_polled_at FROM sources WHERE id = $1
`

func (q *Queries) GetSourceLastPolledAt(ctx context.Context, id int64) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getSourceLastPolledAt, id)
	var last_polled_at *time.Time
	err := row.Scan(&last_polled_at)
	return last_polled_at, err
}

const insertRawItem = `-- name: InsertRawItem :execrows
INSERT INTO raw_items (source_id, external_id, url, url_hash, title, content, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (url_hash) DO NOTHING
`

type InsertRawItemParams struct {
	SourceID    int64
	ExternalID  *string
	Url         string
	UrlHash     []byte
	Title       string
	Content     *string
	PublishedAt *time.Time
}

func (q *Queries) InsertRawItem(ctx context.Context, arg InsertRawItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRawItem,
		arg.SourceID,
		arg.ExternalID,
		arg.Url,
		arg.UrlHash,
		arg.Title,
		arg.Content,
		arg.PublishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDueSourceIDs = `-- name: ListDueSourceIDs :many
SELECT id
FROM sources
WHERE enabled AND (last_polled_at IS NULL OR last_polled_at + poll_interval <= now())
ORDER BY last_polled_at NULLS FIRST, id
`

func (q *Queries) ListDueSourceIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDueSourceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourcePolled = `-- name: MarkSourcePolled :exec
UPDATE sources SET last_polled_at = now() WHERE id = $1
`

func (q *Queries) MarkSourcePolled(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSourcePolled, id)
	return err
}

const recordSourcePoll = `-- name: RecordSourcePoll :exec
UPDATE sources
SET etag = $1, last_modified = $2, last_polled_at = now()
WHERE id = $3
`

type RecordSourcePollParams struct {
	Etag         *string
	LastModified *string
	ID           int64
}

func (q *Queries) RecordSourcePoll(ctx context.Context, arg RecordSourcePollParams) error {
	_, err := q.db.Exec(ctx, recordSourcePoll, arg.Etag, arg.LastModified, arg.ID)
	return err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (name, kind, config, default_topic_ids, poll_interval, enabled)
VALUES ($1, $2, $3, $4, make_interval(secs => $5::bigint), $6)
ON CONFLICT (name) DO UPDATE
SET kind = EXCLUDED.kind,
    config = EXCLUDED.config,
    default_topic_ids = EXCLUDED.default_topic_ids,
    poll_interval = EXCLUDED.poll_interval,
    enabled = EXCLUDED.enabled
RETURNING id
`

type UpsertSourceParams struct {
	Name            string
	Kind            string
	Config          []byte
	DefaultTopicIds []int64
	PollSeconds     int64
	Enabled         bool
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSource,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.DefaultTopicIds,
		arg.PollSeconds,
		arg.Enabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
