// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package db

import (
	"context"
	"time"
)

const addBookmark = `-- name: AddBookmark :exec
INSERT INTO user_bookmarks (user_id, story_id) VALUES ($1, $2)
ON CONFLICT (user_id, story_id) DO NOTHING
`

type AddBookmarkParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) error {
	_, err := q.db.Exec(ctx, addBookmark, arg.UserID, arg.StoryID)
	return err
}

const getStory = `-- name: GetStory :one
SELECT s.id, s.title, s.summary, s.body_md, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    (ub.story_id IS NOT NULL)::boolean AS is_bookmarked,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM stories s
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
WHERE s.id = $2
`

type GetStoryParams struct {
	UserID int64
	ID     int64
}

type GetStoryRow struct {
	ID           int64
	Title        string
	Summary      string
	BodyMd       string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Topics       []string
}

func (q *Queries) GetStory(ctx context.Context, arg GetStoryParams) (GetStoryRow, error) {
	row := q.db.QueryRow(ctx, getStory, arg.UserID, arg.ID)
	var i GetStoryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Kind,
		&i.Severity,
		&i.Importance,
		&i.PublishedAt,
		&i.ReadAt,
		&i.IsBookmarked,
		&i.Topics,
	)
	return i, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    ub.created_at AS bookmarked_at,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM user_bookmarks ub
JOIN stories s ON s.id = ub.story_id
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
WHERE ub.user_id = $1
    AND (
        $2::bigint IS NULL
        OR (ub.created_at, s.id) < ($3::timestamptz, $2::bigint)
    )
ORDER BY ub.created_at DESC, s.id DESC
LIMIT $4
`

type ListBookmarksParams struct {
	UserID     int64
	CursorID   *int64
	CursorTime *time.Time
	PageSize   int32
}

type ListBookmarksRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	BookmarkedAt time.Time
	Topics       []string
}

// The user's bookmarked stories, most recently bookmarked first. Keyset pagination on
// (bookmarked_at, id).
func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks,
		arg.UserID,
		arg.CursorID,
		arg.CursorTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksRow{}
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.BookmarkedAt,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorySources = `-- name: ListStorySources :many
SELECT url, source_name FROM story_sources WHERE story_id = $1 ORDER BY source_name, url
`

type ListStorySourcesRow struct {
	Url        string
	SourceName string
}

func (q *Queries) ListStorySources(ctx context.Context, storyID int64) ([]ListStorySourcesRow, error) {
	rows, err := q.db.Query(ctx, listStorySources, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorySourcesRow{}
	for rows.Next() {
		var i ListStorySourcesRow
		if err := rows.Scan(&i.Url, &i.SourceName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeline = `-- name: ListTimeline :many
WITH RECURSIVE followed AS (
    SELECT ut.topic_id AS id FROM user_topics ut WHERE ut.user_id = $6
    UNION
    SELECT t.id FROM topics t JOIN followed f ON t.parent_id = f.id
), ancestors AS (
    SELECT t.parent_id AS id FROM topics t JOIN user_topics ut ON ut.topic_id = t.id
    WHERE ut.user_id = $6 AND t.parent_id IS NOT NULL
    UNION
    SELECT t.parent_id FROM topics t JOIN ancestors a ON a.id = t.id WHERE t.parent_id IS NOT NULL
), related AS (
    SELECT tr.related_id AS id FROM topic_relations tr JOIN followed f ON f.id = tr.topic_id
    UNION
    SELECT tr.topic_id FROM topic_relations tr JOIN followed f ON f.id = tr.related_id
    UNION
    SELECT a.id FROM ancestors a
), ranked AS (
    SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
        (uss.read_at IS NOT NULL) AS is_read,
        (ub.story_id IS NOT NULL) AS is_bookmarked,
        (CASE
            WHEN EXISTS (SELECT 1 FROM story_topics st JOIN followed f ON f.id = st.topic_id WHERE st.story_id = s.id) THEN 0
            WHEN EXISTS (SELECT 1 FROM story_topics st JOIN related r ON r.id = st.topic_id WHERE st.story_id = s.id) THEN 1
            ELSE 2
        END) AS tier
    FROM stories s
    LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $6
    LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $6
    WHERE s.published_at >= $7
)
SELECT r.id, r.title, r.summary, r.kind, r.severity, r.importance, r.published_at, r.read_at,
    r.is_bookmarked::boolean AS is_bookmarked,
    r.tier::integer AS tier,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = r.id ORDER BY tp.slug
    )::text[] AS topics
FROM ranked r
WHERE $1::bigint IS NULL
    OR r.is_read > $2::boolean
    OR (r.is_read = $2::boolean AND r.tier > $3::integer)
    OR (
        r.is_read = $2::boolean AND r.tier = $3::integer
        AND (r.published_at, r.id) < ($4::timestamptz, $1::bigint)
    )
ORDER BY r.is_read ASC, r.tier ASC, r.published_at DESC, r.id DESC
LIMIT $5
`

type ListTimelineParams struct {
	CursorID          *int64
	CursorRead        *bool
	CursorTier        *int32
	CursorPublishedAt *time.Time
	PageSize          int32
	UserID            int64
	Since             time.Time
}

type ListTimelineRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Tier         int32
	Topics       []string
}

// Every story in the window, ranked by the user's interest: tier 0 is tagged with a followed
// topic (or a descendant of one), tier 1 with a related topic (a relation neighbour or an
// ancestor of a followed topic), tier 2 with anything else. Unread first, then by tier,
// then newest first. Keyset pagination on (is_read, tier, published_at, id).
func (q *Queries) ListTimeline(ctx context.Context, arg ListTimelineParams) ([]ListTimelineRow, error) {
	rows, err := q.db.Query(ctx, listTimeline,
		arg.CursorID,
		arg.CursorRead,
		arg.CursorTier,
		arg.CursorPublishedAt,
		arg.PageSize,
		arg.UserID,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineRow{}
	for rows.Next() {
		var i ListTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.IsBookmarked,
			&i.Tier,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoryRead = `-- name: MarkStoryRead :exec
INSERT INTO user_story_state (user_id, story_id, read_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id, story_id) DO NOTHING
`

type MarkStoryReadParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) MarkStoryRead(ctx context.Context, arg MarkStoryReadParams) error {
	_, err := q.db.Exec(ctx, markStoryRead, arg.UserID, arg.StoryID)
	return err
}

const markStoryUnread = `-- name: MarkStoryUnread :exec
DELETE FROM user_story_state WHERE user_id = $1 AND story_id = $2
`

type MarkStoryUnreadParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) MarkStoryUnread(ctx context.Context, arg MarkStoryUnreadParams) error {
	_, err := q.db.Exec(ctx, markStoryUnread, arg.UserID, arg.StoryID)
	return err
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM user_bookmarks WHERE user_id = $1 AND story_id = $2
`

type RemoveBookmarkParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, removeBookmark, arg.UserID, arg.StoryID)
	return err
}

const searchStories = `-- name: SearchStories :many
SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    (ub.story_id IS NOT NULL)::boolean AS is_bookmarked,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM stories s
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
WHERE s.search @@ websearch_to_tsquery('english', $2::text)
    AND (
        $3::bigint IS NULL
        OR (s.published_at, s.id) < ($4::timestamptz, $3::bigint)
    )
ORDER BY s.published_at DESC, s.id DESC
LIMIT $5
`

type SearchStoriesParams struct {
	UserID            int64
	Query             string
	CursorID          *int64
	CursorPublishedAt *time.Time
	PageSize          int32
}

type SearchStoriesRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Topics       []string
}

// Full-text search over all stories, newest first. Keyset pagination on (published_at, id).
func (q *Queries) SearchStories(ctx context.Context, arg SearchStoriesParams) ([]SearchStoriesRow, error) {
	rows, err := q.db.Query(ctx, searchStories,
		arg.UserID,
		arg.Query,
		arg.CursorID,
		arg.CursorPublishedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStoriesRow{}
	for rows.Next() {
		var i SearchStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.IsBookmarked,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storyExists = `-- name: StoryExists :one
SELECT EXISTS (SELECT 1 FROM stories WHERE id = $1)
`

func (q *Queries) StoryExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, storyExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
