// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package db

import (
	"context"
	"time"
)

const addBookmark = `-- name: AddBookmark :exec
INSERT INTO user_bookmarks (user_id, story_id) VALUES ($1, $2)
ON CONFLICT (user_id, story_id) DO NOTHING
`

type AddBookmarkParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) error {
	_, err := q.db.Exec(ctx, addBookmark, arg.UserID, arg.StoryID)
	return err
}

const addBookmarks = `-- name: AddBookmarks :exec
INSERT INTO user_bookmarks (user_id, story_id)
SELECT $1, s.id FROM stories s WHERE s.id = ANY($2::bigint[])
ON CONFLICT (user_id, story_id) DO NOTHING
`

type AddBookmarksParams struct {
	UserID int64
	Ids    []int64
}

// Batch form of AddBookmark; ids that are not stories are skipped by the join.
func (q *Queries) AddBookmarks(ctx context.Context, arg AddBookmarksParams) error {
	_, err := q.db.Exec(ctx, addBookmarks, arg.UserID, arg.Ids)
	return err
}

const dismissStory = `-- name: DismissStory :exec
INSERT INTO user_story_dismissals (user_id, story_id)
VALUES ($1, $2)
ON CONFLICT (user_id, story_id) DO NOTHING
`

type DismissStoryParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) DismissStory(ctx context.Context, arg DismissStoryParams) error {
	_, err := q.db.Exec(ctx, dismissStory, arg.UserID, arg.StoryID)
	return err
}

const getStory = `-- name: GetStory :one
SELECT s.id, s.title, s.summary, s.body_md, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    (ub.story_id IS NOT NULL)::boolean AS is_bookmarked,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM stories s
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
WHERE s.id = $2
`

type GetStoryParams struct {
	UserID int64
	ID     int64
}

type GetStoryRow struct {
	ID           int64
	Title        string
	Summary      string
	BodyMd       string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Topics       []string
}

func (q *Queries) GetStory(ctx context.Context, arg GetStoryParams) (GetStoryRow, error) {
	row := q.db.QueryRow(ctx, getStory, arg.UserID, arg.ID)
	var i GetStoryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Kind,
		&i.Severity,
		&i.Importance,
		&i.PublishedAt,
		&i.ReadAt,
		&i.IsBookmarked,
		&i.Topics,
	)
	return i, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    ub.created_at AS bookmarked_at,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM user_bookmarks ub
JOIN stories s ON s.id = ub.story_id
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
WHERE ub.user_id = $1
    AND (
        $2::bigint IS NULL
        OR (ub.created_at, s.id) < ($3::timestamptz, $2::bigint)
    )
ORDER BY ub.created_at DESC, s.id DESC
LIMIT $4
`

type ListBookmarksParams struct {
	UserID     int64
	CursorID   *int64
	CursorTime *time.Time
	PageSize   int32
}

type ListBookmarksRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	BookmarkedAt time.Time
	Topics       []string
}

// The user's bookmarked stories, most recently bookmarked first. Keyset pagination on
// (bookmarked_at, id).
func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks,
		arg.UserID,
		arg.CursorID,
		arg.CursorTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksRow{}
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.BookmarkedAt,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorySources = `-- name: ListStorySources :many
SELECT url, source_name FROM story_sources WHERE story_id = $1 ORDER BY source_name, url
`

type ListStorySourcesRow struct {
	Url        string
	SourceName string
}

func (q *Queries) ListStorySources(ctx context.Context, storyID int64) ([]ListStorySourcesRow, error) {
	rows, err := q.db.Query(ctx, listStorySources, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorySourcesRow{}
	for rows.Next() {
		var i ListStorySourcesRow
		if err := rows.Scan(&i.Url, &i.SourceName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeline = `-- name: ListTimeline :many
WITH RECURSIVE followed AS (
    SELECT ut.topic_id AS id FROM user_topics ut WHERE ut.user_id = $1
    UNION
    SELECT t.id FROM topics t JOIN followed f ON t.parent_id = f.id
    WHERE NOT EXISTS (SELECT 1 FROM user_topic_mutes um WHERE um.user_id = $1 AND um.topic_id = t.id)
), muted AS (
    SELECT um.topic_id AS id FROM user_topic_mutes um WHERE um.user_id = $1
    UNION
    SELECT t.id FROM topics t JOIN muted m ON t.parent_id = m.id
    WHERE NOT EXISTS (SELECT 1 FROM user_topics ut WHERE ut.user_id = $1 AND ut.topic_id = t.id)
), ancestors AS (
    SELECT t.parent_id AS id FROM topics t JOIN user_topics ut ON ut.topic_id = t.id
    WHERE ut.user_id = $1 AND t.parent_id IS NOT NULL
    UNION
    SELECT t.parent_id FROM topics t JOIN ancestors a ON a.id = t.id WHERE t.parent_id IS NOT NULL
), affinity AS (
    SELECT DISTINCT st.topic_id AS id
    FROM story_topics st
    JOIN (
        SELECT r.story_id FROM user_story_state r
        WHERE r.user_id = $1 AND r.read_at >= $2::timestamptz AND r.read_at < $3::timestamptz
        UNION
        SELECT b.story_id FROM user_bookmarks b
        WHERE b.user_id = $1 AND b.created_at >= $2::timestamptz AND b.created_at < $3::timestamptz
    ) e ON e.story_id = st.story_id
), profession AS (
    SELECT pt.topic_id AS id
    FROM user_professions up JOIN profession_topics pt ON pt.profession_id = up.profession_id
    WHERE up.user_id = $1
    UNION
    SELECT t.id FROM topics t JOIN profession p ON t.parent_id = p.id
), headline AS (
    SELECT t.id FROM topics t WHERE t.headline
    UNION
    SELECT t.id FROM topics t JOIN headline h ON t.parent_id = h.id
), topic_tier AS (
    SELECT f.id, 0 AS tier FROM followed f
    UNION ALL
    SELECT af.id, 1 FROM affinity af
    UNION ALL
    SELECT p.id, 2 FROM profession p
    UNION ALL
    SELECT tr.related_id, 3 FROM topic_relations tr JOIN followed f ON f.id = tr.topic_id
    UNION ALL
    SELECT tr.topic_id, 3 FROM topic_relations tr JOIN followed f ON f.id = tr.related_id
    UNION ALL
    SELECT a.id, 3 FROM ancestors a
    UNION ALL
    SELECT h.id, 4 FROM headline h
), story_tier AS (
    SELECT st.story_id, min(tt.tier) AS tier
    FROM story_topics st JOIN topic_tier tt ON tt.id = st.topic_id
    WHERE NOT EXISTS (SELECT 1 FROM muted m WHERE m.id = tt.id)
    GROUP BY st.story_id
), muted_story AS (
    -- Stories with at least one muted topic, kept when every one of their topics is muted.
    SELECT st.story_id
    FROM story_topics st LEFT JOIN muted m ON m.id = st.topic_id
    WHERE st.story_id IN (SELECT ms.story_id FROM story_topics ms JOIN muted mm ON mm.id = ms.topic_id)
    GROUP BY st.story_id
    HAVING count(m.id) = count(*)
), ranked AS (
    SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
        (uss.read_at IS NOT NULL) AS is_read,
        (ub.story_id IS NOT NULL) AS is_bookmarked,
        CASE WHEN stt.tier = 4 AND s.importance < $4::smallint THEN 5
            ELSE COALESCE(stt.tier, 5) END AS tier,
        sv.seen_at
    FROM stories s
    LEFT JOIN story_tier stt ON stt.story_id = s.id
    LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
    LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
    LEFT JOIN story_views sv ON sv.story_id = s.id AND sv.user_id = $1
    LEFT JOIN user_story_dismissals usd ON usd.story_id = s.id AND usd.user_id = $1
    LEFT JOIN muted_story ms ON ms.story_id = s.id
    WHERE s.published_at >= $5
    AND usd.story_id IS NULL
    AND ms.story_id IS NULL
    AND (
        s.kind <> 'deal' OR cardinality(s.countries) = 0
        OR (SELECT u.country FROM users u WHERE u.id = $1) = ANY(s.countries)
    )
    AND (cardinality($6::text[]) = 0 OR s.kind = ANY($6::text[]))
    AND ($7::boolean IS NULL OR (uss.read_at IS NOT NULL) = $7::boolean)
), scored AS (
    -- sqlc.arg, not @name: sqlc fails to resolve the ranked alias in arithmetic with @name params.
    SELECT r.id, r.title, r.summary, r.kind, r.severity, r.importance, r.published_at, r.read_at, r.is_read, r.is_bookmarked, r.tier, r.seen_at,
        CASE WHEN r.is_read THEN 0 ELSE
            $8::float8 * r.importance
            -- Affinity sits half a step below followed, so every other tier keeps its points.
            - $9::float8 * CASE r.tier WHEN 0 THEN 0 WHEN 1 THEN 0.5 ELSE r.tier - 1 END
            + $10::float8
                * CASE r.severity WHEN 'critical' THEN 3 WHEN 'high' THEN 2 WHEN 'medium' THEN 1 ELSE 0 END
            - extract(epoch FROM greatest($3::timestamptz - r.published_at, interval '0'))
                / 3600 / $11::float8
            - CASE WHEN r.seen_at < $12::timestamptz AND NOT r.is_bookmarked AND r.tier > 0
                THEN $13::float8 ELSE 0 END
        END::float8 AS score,
        (NOT r.is_read AND r.tier = 0) AS is_followed
    FROM ranked r
    WHERE r.tier < 5 OR r.importance >= $14::smallint
        OR NOT (
            EXISTS (SELECT 1 FROM user_topics ut WHERE ut.user_id = $1)
            OR EXISTS (SELECT 1 FROM user_professions up WHERE up.user_id = $1)
        )
), page AS (
    SELECT sc.id, sc.title, sc.summary, sc.kind, sc.severity, sc.importance, sc.published_at, sc.read_at, sc.is_read, sc.is_bookmarked, sc.tier, sc.seen_at, sc.score, sc.is_followed FROM scored sc
    WHERE $15::bigint IS NULL
        OR sc.is_read > $16::boolean
        OR (
            sc.is_read = $16::boolean
            AND (
                sc.is_followed < $17::boolean
                OR (
                    sc.is_followed = $17::boolean
                    AND (sc.score, sc.published_at, sc.id) < (
                        $18::float8, $19::timestamptz, $15::bigint
                    )
                )
            )
        )
    ORDER BY sc.is_read ASC, sc.is_followed DESC, sc.score DESC, sc.published_at DESC, sc.id DESC
    LIMIT $20
)
SELECT p.id, p.title, p.summary, p.kind, p.severity, p.importance, p.published_at, p.read_at,
    p.is_bookmarked::boolean AS is_bookmarked,
    p.tier::integer AS tier,
    p.score::float8 AS score,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = p.id ORDER BY tp.slug
    )::text[] AS topics
FROM page p
ORDER BY p.is_read ASC, p.is_followed DESC, p.score DESC, p.published_at DESC, p.id DESC
`

type ListTimelineParams struct {
	UserID                int64
	AffinitySince         time.Time
	AsOf                  time.Time
	HeadlineMinImportance int16
	Since                 time.Time
	Kinds                 []string
	ReadFilter            *bool
	ImportanceWeight      float64
	TierWeight            float64
	SeverityWeight        float64
	DecayHours            float64
	SeenBefore            time.Time
	SeenPenalty           float64
	ExploreMinImportance  int16
	CursorID              *int64
	CursorRead            *bool
	CursorFollowed        *bool
	CursorScore           *float64
	CursorPublishedAt     *time.Time
	PageSize              int32
}

type ListTimelineRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Tier         int32
	Score        float64
	Topics       []string
}

// Every story in the window (deals only for the user's country, or global ones), ranked by the user's interest: tier 0 is tagged with a followed
// topic (or a descendant of one), tier 1 (affinity) with a topic of a story the user read or saved
// between affinity_since and as_of, tier 2 with an area of one of the user's professions (or a
// descendant), tier 3 with a related topic (a relation neighbour or an ancestor of a followed
// topic), tier 4 with a headline topic (or a descendant) and of at least @headline_min_importance,
// tier 5 (explore) with anything else, and only when of at least explore_min_importance or the user
// follows nothing and has no profession. Unread first, by score: tier, importance and severity points minus
// one point per decay_hours of age at as_of, minus seen_penalty for a story first seen before
// seen_before and not saved (never for a followed topic). Read stories (score 0) follow, newest first. Every input is fixed
// for a given as_of, so later views or new stories don't move rows across a page boundary.
// Feedback: dismissed stories are left out. A muted topic covers its descendants down to (not
// including) a followed one, and following likewise stops at a muted descendant, so the most
// specific choice wins. Muted topics give no tier, and a story whose every topic is muted is left out.
// Optional filters: kinds (empty means all) and read_filter (NULL both, true read only, false unread only).
// Unread stories of a followed topic (tier 0) come before every other unread story, whatever their score.
// Keyset pagination on (is_read, is_followed, score, published_at, id).
// Tiers come from one aggregate over the in-tier topics' story_topics rows instead of per-story
// subqueries, and topic slugs are built only for the page: per-row subplans over the whole window
// inflated the plan cost past jit_above_cost, and JIT compilation took ~90% of the query time.
func (q *Queries) ListTimeline(ctx context.Context, arg ListTimelineParams) ([]ListTimelineRow, error) {
	rows, err := q.db.Query(ctx, listTimeline,
		arg.UserID,
		arg.AffinitySince,
		arg.AsOf,
		arg.HeadlineMinImportance,
		arg.Since,
		arg.Kinds,
		arg.ReadFilter,
		arg.ImportanceWeight,
		arg.TierWeight,
		arg.SeverityWeight,
		arg.DecayHours,
		arg.SeenBefore,
		arg.SeenPenalty,
		arg.ExploreMinImportance,
		arg.CursorID,
		arg.CursorRead,
		arg.CursorFollowed,
		arg.CursorScore,
		arg.CursorPublishedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineRow{}
	for rows.Next() {
		var i ListTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.IsBookmarked,
			&i.Tier,
			&i.Score,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoryRead = `-- name: MarkStoryRead :exec
INSERT INTO user_story_state (user_id, story_id, read_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id, story_id) DO NOTHING
`

type MarkStoryReadParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) MarkStoryRead(ctx context.Context, arg MarkStoryReadParams) error {
	_, err := q.db.Exec(ctx, markStoryRead, arg.UserID, arg.StoryID)
	return err
}

const markStoryUnread = `-- name: MarkStoryUnread :exec
DELETE FROM user_story_state WHERE user_id = $1 AND story_id = $2
`

type MarkStoryUnreadParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) MarkStoryUnread(ctx context.Context, arg MarkStoryUnreadParams) error {
	_, err := q.db.Exec(ctx, markStoryUnread, arg.UserID, arg.StoryID)
	return err
}

const recordStoryViews = `-- name: RecordStoryViews :exec
INSERT INTO story_views (user_id, story_id)
SELECT $1, s.id FROM stories s WHERE s.id = ANY($2::bigint[])
ON CONFLICT DO NOTHING
`

type RecordStoryViewsParams struct {
	UserID int64
	Ids    []int64
}

// Idempotent; ids that are not stories are skipped by the join.
func (q *Queries) RecordStoryViews(ctx context.Context, arg RecordStoryViewsParams) error {
	_, err := q.db.Exec(ctx, recordStoryViews, arg.UserID, arg.Ids)
	return err
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM user_bookmarks WHERE user_id = $1 AND story_id = $2
`

type RemoveBookmarkParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, removeBookmark, arg.UserID, arg.StoryID)
	return err
}

const removeBookmarks = `-- name: RemoveBookmarks :exec
DELETE FROM user_bookmarks WHERE user_id = $1 AND story_id = ANY($2::bigint[])
`

type RemoveBookmarksParams struct {
	UserID int64
	Ids    []int64
}

func (q *Queries) RemoveBookmarks(ctx context.Context, arg RemoveBookmarksParams) error {
	_, err := q.db.Exec(ctx, removeBookmarks, arg.UserID, arg.Ids)
	return err
}

const searchStories = `-- name: SearchStories :many
SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    (ub.story_id IS NOT NULL)::boolean AS is_bookmarked,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM stories s
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
WHERE (
        s.search @@ websearch_to_tsquery('english', $2::text)
        OR word_similarity($2::text, s.title) >= 0.4
    )
    AND (
        s.kind <> 'deal' OR cardinality(s.countries) = 0
        OR (SELECT u.country FROM users u WHERE u.id = $1) = ANY(s.countries)
    )
    AND (
        $3::bigint IS NULL
        OR (s.published_at, s.id) < ($4::timestamptz, $3::bigint)
    )
ORDER BY s.published_at DESC, s.id DESC
LIMIT $5
`

type SearchStoriesParams struct {
	UserID            int64
	Query             string
	CursorID          *int64
	CursorPublishedAt *time.Time
	PageSize          int32
}

type SearchStoriesRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Topics       []string
}

// Full-text search over all stories visible to the user, newest first; titles also match fuzzily (typos) by trigram
// word similarity. Keyset pagination on (published_at, id).
func (q *Queries) SearchStories(ctx context.Context, arg SearchStoriesParams) ([]SearchStoriesRow, error) {
	rows, err := q.db.Query(ctx, searchStories,
		arg.UserID,
		arg.Query,
		arg.CursorID,
		arg.CursorPublishedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStoriesRow{}
	for rows.Next() {
		var i SearchStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.IsBookmarked,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storyExists = `-- name: StoryExists :one
SELECT EXISTS (SELECT 1 FROM stories WHERE id = $1)
`

func (q *Queries) StoryExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, storyExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const undismissStory = `-- name: UndismissStory :exec
DELETE FROM user_story_dismissals WHERE user_id = $1 AND story_id = $2
`

type UndismissStoryParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) UndismissStory(ctx context.Context, arg UndismissStoryParams) error {
	_, err := q.db.Exec(ctx, undismissStory, arg.UserID, arg.StoryID)
	return err
}
