// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package db

import (
	"context"
	"time"
)

const addBookmark = `-- name: AddBookmark :exec
INSERT INTO user_bookmarks (user_id, story_id) VALUES ($1, $2)
ON CONFLICT (user_id, story_id) DO NOTHING
`

type AddBookmarkParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) error {
	_, err := q.db.Exec(ctx, addBookmark, arg.UserID, arg.StoryID)
	return err
}

const addBookmarks = `-- name: AddBookmarks :exec
INSERT INTO user_bookmarks (user_id, story_id)
SELECT $1, s.id FROM stories s WHERE s.id = ANY($2::bigint[])
ON CONFLICT (user_id, story_id) DO NOTHING
`

type AddBookmarksParams struct {
	UserID int64
	Ids    []int64
}

// Batch form of AddBookmark; ids that are not stories are skipped by the join.
func (q *Queries) AddBookmarks(ctx context.Context, arg AddBookmarksParams) error {
	_, err := q.db.Exec(ctx, addBookmarks, arg.UserID, arg.Ids)
	return err
}

const getStory = `-- name: GetStory :one
SELECT s.id, s.title, s.summary, s.body_md, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    (ub.story_id IS NOT NULL)::boolean AS is_bookmarked,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM stories s
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
WHERE s.id = $2
`

type GetStoryParams struct {
	UserID int64
	ID     int64
}

type GetStoryRow struct {
	ID           int64
	Title        string
	Summary      string
	BodyMd       string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Topics       []string
}

func (q *Queries) GetStory(ctx context.Context, arg GetStoryParams) (GetStoryRow, error) {
	row := q.db.QueryRow(ctx, getStory, arg.UserID, arg.ID)
	var i GetStoryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Kind,
		&i.Severity,
		&i.Importance,
		&i.PublishedAt,
		&i.ReadAt,
		&i.IsBookmarked,
		&i.Topics,
	)
	return i, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    ub.created_at AS bookmarked_at,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM user_bookmarks ub
JOIN stories s ON s.id = ub.story_id
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
WHERE ub.user_id = $1
    AND (
        $2::bigint IS NULL
        OR (ub.created_at, s.id) < ($3::timestamptz, $2::bigint)
    )
ORDER BY ub.created_at DESC, s.id DESC
LIMIT $4
`

type ListBookmarksParams struct {
	UserID     int64
	CursorID   *int64
	CursorTime *time.Time
	PageSize   int32
}

type ListBookmarksRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	BookmarkedAt time.Time
	Topics       []string
}

// The user's bookmarked stories, most recently bookmarked first. Keyset pagination on
// (bookmarked_at, id).
func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks,
		arg.UserID,
		arg.CursorID,
		arg.CursorTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksRow{}
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.BookmarkedAt,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorySources = `-- name: ListStorySources :many
SELECT url, source_name FROM story_sources WHERE story_id = $1 ORDER BY source_name, url
`

type ListStorySourcesRow struct {
	Url        string
	SourceName string
}

func (q *Queries) ListStorySources(ctx context.Context, storyID int64) ([]ListStorySourcesRow, error) {
	rows, err := q.db.Query(ctx, listStorySources, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorySourcesRow{}
	for rows.Next() {
		var i ListStorySourcesRow
		if err := rows.Scan(&i.Url, &i.SourceName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeline = `-- name: ListTimeline :many
WITH RECURSIVE followed AS (
    SELECT ut.topic_id AS id FROM user_topics ut WHERE ut.user_id = $1
    UNION
    SELECT t.id FROM topics t JOIN followed f ON t.parent_id = f.id
), ancestors AS (
    SELECT t.parent_id AS id FROM topics t JOIN user_topics ut ON ut.topic_id = t.id
    WHERE ut.user_id = $1 AND t.parent_id IS NOT NULL
    UNION
    SELECT t.parent_id FROM topics t JOIN ancestors a ON a.id = t.id WHERE t.parent_id IS NOT NULL
), profession AS (
    SELECT pt.topic_id AS id
    FROM user_professions up JOIN profession_topics pt ON pt.profession_id = up.profession_id
    WHERE up.user_id = $1
    UNION
    SELECT t.id FROM topics t JOIN profession p ON t.parent_id = p.id
), topic_tier AS (
    SELECT f.id, 0 AS tier FROM followed f
    UNION ALL
    SELECT p.id, 1 FROM profession p
    UNION ALL
    SELECT tr.related_id, 2 FROM topic_relations tr JOIN followed f ON f.id = tr.topic_id
    UNION ALL
    SELECT tr.topic_id, 2 FROM topic_relations tr JOIN followed f ON f.id = tr.related_id
    UNION ALL
    SELECT a.id, 2 FROM ancestors a
), story_tier AS (
    SELECT st.story_id, min(tt.tier) AS tier
    FROM story_topics st JOIN topic_tier tt ON tt.id = st.topic_id
    GROUP BY st.story_id
), ranked AS (
    SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
        (uss.read_at IS NOT NULL) AS is_read,
        (ub.story_id IS NOT NULL) AS is_bookmarked,
        COALESCE(stt.tier, 3) AS tier
    FROM stories s
    LEFT JOIN story_tier stt ON stt.story_id = s.id
    LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
    LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
    WHERE s.published_at >= $2
    AND (
        s.kind <> 'deal' OR cardinality(s.countries) = 0
        OR (SELECT u.country FROM users u WHERE u.id = $1) = ANY(s.countries)
    )
    AND (cardinality($3::text[]) = 0 OR s.kind = ANY($3::text[]))
    AND ($4::boolean IS NULL OR (uss.read_at IS NOT NULL) = $4::boolean)
), page AS (
    SELECT r.id, r.title, r.summary, r.kind, r.severity, r.importance, r.published_at, r.read_at, r.is_read, r.is_bookmarked, r.tier FROM ranked r
    WHERE $5::bigint IS NULL
        OR r.is_read > $6::boolean
        OR (r.is_read = $6::boolean AND r.tier > $7::integer)
        OR (
            r.is_read = $6::boolean AND r.tier = $7::integer
            AND (r.published_at, r.id) < ($8::timestamptz, $5::bigint)
        )
    ORDER BY r.is_read ASC, r.tier ASC, r.published_at DESC, r.id DESC
    LIMIT $9
)
SELECT p.id, p.title, p.summary, p.kind, p.severity, p.importance, p.published_at, p.read_at,
    p.is_bookmarked::boolean AS is_bookmarked,
    p.tier::integer AS tier,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = p.id ORDER BY tp.slug
    )::text[] AS topics
FROM page p
ORDER BY p.is_read ASC, p.tier ASC, p.published_at DESC, p.id DESC
`

type ListTimelineParams struct {
	UserID            int64
	Since             time.Time
	Kinds             []string
	ReadFilter        *bool
	CursorID          *int64
	CursorRead        *bool
	CursorTier        *int32
	CursorPublishedAt *time.Time
	PageSize          int32
}

type ListTimelineRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Tier         int32
	Topics       []string
}

// Every story in the window (deals only for the user's country, or global ones), ranked by the user's interest: tier 0 is tagged with a followed
// topic (or a descendant of one), tier 1 with an area of one of the user's professions (or a
// descendant), tier 2 with a related topic (a relation neighbour or an ancestor of a followed
// topic), tier 3 with anything else. Unread first, then by tier,
// then newest first. Optional filters: kinds (empty means all) and read_filter (NULL both, true read only, false unread only).
// Keyset pagination on (is_read, tier, published_at, id).
// Tiers come from one aggregate over the in-tier topics' story_topics rows instead of per-story
// subqueries, and topic slugs are built only for the page: per-row subplans over the whole window
// inflated the plan cost past jit_above_cost, and JIT compilation took ~90% of the query time.
func (q *Queries) ListTimeline(ctx context.Context, arg ListTimelineParams) ([]ListTimelineRow, error) {
	rows, err := q.db.Query(ctx, listTimeline,
		arg.UserID,
		arg.Since,
		arg.Kinds,
		arg.ReadFilter,
		arg.CursorID,
		arg.CursorRead,
		arg.CursorTier,
		arg.CursorPublishedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineRow{}
	for rows.Next() {
		var i ListTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.IsBookmarked,
			&i.Tier,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStoryRead = `-- name: MarkStoryRead :exec
INSERT INTO user_story_state (user_id, story_id, read_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id, story_id) DO NOTHING
`

type MarkStoryReadParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) MarkStoryRead(ctx context.Context, arg MarkStoryReadParams) error {
	_, err := q.db.Exec(ctx, markStoryRead, arg.UserID, arg.StoryID)
	return err
}

const markStoryUnread = `-- name: MarkStoryUnread :exec
DELETE FROM user_story_state WHERE user_id = $1 AND story_id = $2
`

type MarkStoryUnreadParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) MarkStoryUnread(ctx context.Context, arg MarkStoryUnreadParams) error {
	_, err := q.db.Exec(ctx, markStoryUnread, arg.UserID, arg.StoryID)
	return err
}

const recordStoryViews = `-- name: RecordStoryViews :exec
INSERT INTO story_views (user_id, story_id)
SELECT $1, s.id FROM stories s WHERE s.id = ANY($2::bigint[])
ON CONFLICT DO NOTHING
`

type RecordStoryViewsParams struct {
	UserID int64
	Ids    []int64
}

// Idempotent; ids that are not stories are skipped by the join.
func (q *Queries) RecordStoryViews(ctx context.Context, arg RecordStoryViewsParams) error {
	_, err := q.db.Exec(ctx, recordStoryViews, arg.UserID, arg.Ids)
	return err
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM user_bookmarks WHERE user_id = $1 AND story_id = $2
`

type RemoveBookmarkParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, removeBookmark, arg.UserID, arg.StoryID)
	return err
}

const removeBookmarks = `-- name: RemoveBookmarks :exec
DELETE FROM user_bookmarks WHERE user_id = $1 AND story_id = ANY($2::bigint[])
`

type RemoveBookmarksParams struct {
	UserID int64
	Ids    []int64
}

func (q *Queries) RemoveBookmarks(ctx context.Context, arg RemoveBookmarksParams) error {
	_, err := q.db.Exec(ctx, removeBookmarks, arg.UserID, arg.Ids)
	return err
}

const searchStories = `-- name: SearchStories :many
SELECT s.id, s.title, s.summary, s.kind, s.severity, s.importance, s.published_at, uss.read_at,
    (ub.story_id IS NOT NULL)::boolean AS is_bookmarked,
    ARRAY(
        SELECT tp.slug FROM story_topics stp JOIN topics tp ON tp.id = stp.topic_id
        WHERE stp.story_id = s.id ORDER BY tp.slug
    )::text[] AS topics
FROM stories s
LEFT JOIN user_story_state uss ON uss.story_id = s.id AND uss.user_id = $1
LEFT JOIN user_bookmarks ub ON ub.story_id = s.id AND ub.user_id = $1
WHERE (
        s.search @@ websearch_to_tsquery('english', $2::text)
        OR word_similarity($2::text, s.title) >= 0.4
    )
    AND (
        s.kind <> 'deal' OR cardinality(s.countries) = 0
        OR (SELECT u.country FROM users u WHERE u.id = $1) = ANY(s.countries)
    )
    AND (
        $3::bigint IS NULL
        OR (s.published_at, s.id) < ($4::timestamptz, $3::bigint)
    )
ORDER BY s.published_at DESC, s.id DESC
LIMIT $5
`

type SearchStoriesParams struct {
	UserID            int64
	Query             string
	CursorID          *int64
	CursorPublishedAt *time.Time
	PageSize          int32
}

type SearchStoriesRow struct {
	ID           int64
	Title        string
	Summary      string
	Kind         string
	Severity     *string
	Importance   int16
	PublishedAt  time.Time
	ReadAt       *time.Time
	IsBookmarked bool
	Topics       []string
}

// Full-text search over all stories visible to the user, newest first; titles also match fuzzily (typos) by trigram
// word similarity. Keyset pagination on (published_at, id).
func (q *Queries) SearchStories(ctx context.Context, arg SearchStoriesParams) ([]SearchStoriesRow, error) {
	rows, err := q.db.Query(ctx, searchStories,
		arg.UserID,
		arg.Query,
		arg.CursorID,
		arg.CursorPublishedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStoriesRow{}
	for rows.Next() {
		var i SearchStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.Severity,
			&i.Importance,
			&i.PublishedAt,
			&i.ReadAt,
			&i.IsBookmarked,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storyExists = `-- name: StoryExists :one
SELECT EXISTS (SELECT 1 FROM stories WHERE id = $1)
`

func (q *Queries) StoryExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, storyExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
