// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic_requests.sql

package db

import (
	"context"
	"time"
)

const countPendingTopicRequests = `-- name: CountPendingTopicRequests :one
SELECT count(*) FROM topic_requests WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingTopicRequests(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingTopicRequests, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTopicRequest = `-- name: CreateTopicRequest :one
INSERT INTO topic_requests (user_id, text) VALUES ($1, $2)
RETURNING id, text, status, note, created_at, resolved_at
`

type CreateTopicRequestParams struct {
	UserID int64
	Text   string
}

type CreateTopicRequestRow struct {
	ID         int64
	Text       string
	Status     string
	Note       *string
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

func (q *Queries) CreateTopicRequest(ctx context.Context, arg CreateTopicRequestParams) (CreateTopicRequestRow, error) {
	row := q.db.QueryRow(ctx, createTopicRequest, arg.UserID, arg.Text)
	var i CreateTopicRequestRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listMyTopicRequests = `-- name: ListMyTopicRequests :many
SELECT tr.id, tr.text, tr.status, t.slug AS topic_slug, tr.note, tr.created_at, tr.resolved_at
FROM topic_requests tr
LEFT JOIN topics t ON t.id = tr.topic_id
WHERE tr.user_id = $1
ORDER BY tr.created_at DESC, tr.id DESC
LIMIT $2
`

type ListMyTopicRequestsParams struct {
	UserID  int64
	MaxRows int32
}

type ListMyTopicRequestsRow struct {
	ID         int64
	Text       string
	Status     string
	TopicSlug  *string
	Note       *string
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

// The user's topic requests, newest first, with the slug of the topic each was resolved to.
func (q *Queries) ListMyTopicRequests(ctx context.Context, arg ListMyTopicRequestsParams) ([]ListMyTopicRequestsRow, error) {
	rows, err := q.db.Query(ctx, listMyTopicRequests, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTopicRequestsRow{}
	for rows.Next() {
		var i ListMyTopicRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.TopicSlug,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserTopicRequests = `-- name: LockUserTopicRequests :exec
SELECT pg_advisory_xact_lock(hashtextextended('topic_requests:' || $1::bigint, 0))
`

// Serializes topic-request creation per user until the transaction ends, so the pending cap holds.
func (q *Queries) LockUserTopicRequests(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, lockUserTopicRequests, userID)
	return err
}
