// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package db

import (
	"context"
)

const deleteProfessionTopics = `-- name: DeleteProfessionTopics :exec
DELETE FROM profession_topics WHERE profession_id = $1
`

func (q *Queries) DeleteProfessionTopics(ctx context.Context, professionID int64) error {
	_, err := q.db.Exec(ctx, deleteProfessionTopics, professionID)
	return err
}

const getProfessionIDsBySlugs = `-- name: GetProfessionIDsBySlugs :many
SELECT id, slug FROM professions WHERE slug = ANY($1::text[])
`

type GetProfessionIDsBySlugsRow struct {
	ID   int64
	Slug string
}

func (q *Queries) GetProfessionIDsBySlugs(ctx context.Context, slugs []string) ([]GetProfessionIDsBySlugsRow, error) {
	rows, err := q.db.Query(ctx, getProfessionIDsBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfessionIDsBySlugsRow{}
	for rows.Next() {
		var i GetProfessionIDsBySlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicIDsBySlugs = `-- name: GetTopicIDsBySlugs :many
SELECT id, slug FROM topics WHERE slug = ANY($1::text[])
`

type GetTopicIDsBySlugsRow struct {
	ID   int64
	Slug string
}

func (q *Queries) GetTopicIDsBySlugs(ctx context.Context, slugs []string) ([]GetTopicIDsBySlugsRow, error) {
	rows, err := q.db.Query(ctx, getTopicIDsBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopicIDsBySlugsRow{}
	for rows.Next() {
		var i GetTopicIDsBySlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProfessionTopics = `-- name: InsertProfessionTopics :exec
INSERT INTO profession_topics (profession_id, topic_id, position)
SELECT $1, t.id, (u.ord - 1)::smallint
FROM unnest($2::text[]) WITH ORDINALITY AS u(slug, ord)
JOIN topics t ON t.slug = u.slug
`

type InsertProfessionTopicsParams struct {
	ProfessionID int64
	TopicSlugs   []string
}

func (q *Queries) InsertProfessionTopics(ctx context.Context, arg InsertProfessionTopicsParams) error {
	_, err := q.db.Exec(ctx, insertProfessionTopics, arg.ProfessionID, arg.TopicSlugs)
	return err
}

const listFollowedTopics = `-- name: ListFollowedTopics :many
SELECT t.slug, t.name, t.description
FROM topics t
WHERE EXISTS (SELECT 1 FROM user_topics ut WHERE ut.topic_id = t.id)
ORDER BY t.slug
`

type ListFollowedTopicsRow struct {
	Slug        string
	Name        string
	Description string
}

// Topics followed by at least one user.
func (q *Queries) ListFollowedTopics(ctx context.Context) ([]ListFollowedTopicsRow, error) {
	rows, err := q.db.Query(ctx, listFollowedTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowedTopicsRow{}
	for rows.Next() {
		var i ListFollowedTopicsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfessions = `-- name: ListProfessions :many
SELECT p.slug, p.name, p.description, p.launched,
    COALESCE(
        array_agg(t.slug ORDER BY pt.position, t.slug) FILTER (WHERE t.id IS NOT NULL),
        '{}'
    )::text[] AS topics
FROM professions p
LEFT JOIN profession_topics pt ON pt.profession_id = p.id
LEFT JOIN topics t ON t.id = pt.topic_id
GROUP BY p.id
ORDER BY p.name, p.slug
`

type ListProfessionsRow struct {
	Slug        string
	Name        string
	Description string
	Launched    bool
	Topics      []string
}

func (q *Queries) ListProfessions(ctx context.Context) ([]ListProfessionsRow, error) {
	rows, err := q.db.Query(ctx, listProfessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfessionsRow{}
	for rows.Next() {
		var i ListProfessionsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Launched,
			&i.Topics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT t.slug, t.name, p.slug AS parent_slug, t.description, t.headline
FROM topics t
LEFT JOIN topics p ON p.id = t.parent_id
ORDER BY t.slug
`

type ListTopicsRow struct {
	Slug        string
	Name        string
	ParentSlug  *string
	Description string
	Headline    bool
}

func (q *Queries) ListTopics(ctx context.Context) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicsRow{}
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.ParentSlug,
			&i.Description,
			&i.Headline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfession = `-- name: UpsertProfession :one
INSERT INTO professions (slug, name, description, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description, position = EXCLUDED.position, updated_at = now()
RETURNING id
`

type UpsertProfessionParams struct {
	Slug        string
	Name        string
	Description string
	Position    int16
}

func (q *Queries) UpsertProfession(ctx context.Context, arg UpsertProfessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertProfession,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (slug, name, parent_id, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name, parent_id = EXCLUDED.parent_id, description = EXCLUDED.description
RETURNING id
`

type UpsertTopicParams struct {
	Slug        string
	Name        string
	ParentID    *int64
	Description string
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTopic,
		arg.Slug,
		arg.Name,
		arg.ParentID,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
