// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package db

import (
	"context"
)

const getTopicIDsBySlugs = `-- name: GetTopicIDsBySlugs :many
SELECT id, slug FROM topics WHERE slug = ANY($1::text[])
`

type GetTopicIDsBySlugsRow struct {
	ID   int64
	Slug string
}

func (q *Queries) GetTopicIDsBySlugs(ctx context.Context, slugs []string) ([]GetTopicIDsBySlugsRow, error) {
	rows, err := q.db.Query(ctx, getTopicIDsBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopicIDsBySlugsRow{}
	for rows.Next() {
		var i GetTopicIDsBySlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowedTopics = `-- name: ListFollowedTopics :many
SELECT t.slug, t.name, t.description
FROM topics t
WHERE EXISTS (SELECT 1 FROM user_topics ut WHERE ut.topic_id = t.id)
ORDER BY t.slug
`

type ListFollowedTopicsRow struct {
	Slug        string
	Name        string
	Description string
}

// Topics followed by at least one user.
func (q *Queries) ListFollowedTopics(ctx context.Context) ([]ListFollowedTopicsRow, error) {
	rows, err := q.db.Query(ctx, listFollowedTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowedTopicsRow{}
	for rows.Next() {
		var i ListFollowedTopicsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT t.slug, t.name, p.slug AS parent_slug, t.description
FROM topics t
LEFT JOIN topics p ON p.id = t.parent_id
ORDER BY t.slug
`

type ListTopicsRow struct {
	Slug        string
	Name        string
	ParentSlug  *string
	Description string
}

func (q *Queries) ListTopics(ctx context.Context) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicsRow{}
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.ParentSlug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (slug, name, parent_id, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name, parent_id = EXCLUDED.parent_id, description = EXCLUDED.description
RETURNING id
`

type UpsertTopicParams struct {
	Slug        string
	Name        string
	ParentID    *int64
	Description string
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTopic,
		arg.Slug,
		arg.Name,
		arg.ParentID,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
