// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// Deleting the user cascades to their follows, mutes, read and dismissed state, bookmarks, devices and topic
// requests.
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserProfessions = `-- name: DeleteUserProfessions :exec
DELETE FROM user_professions WHERE user_id = $1
`

func (q *Queries) DeleteUserProfessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserProfessions, userID)
	return err
}

const deleteUserTopicMutes = `-- name: DeleteUserTopicMutes :exec
DELETE FROM user_topic_mutes WHERE user_id = $1
`

func (q *Queries) DeleteUserTopicMutes(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserTopicMutes, userID)
	return err
}

const deleteUserTopicMutesByIDs = `-- name: DeleteUserTopicMutesByIDs :exec
DELETE FROM user_topic_mutes WHERE user_id = $1 AND topic_id = ANY($2::bigint[])
`

type DeleteUserTopicMutesByIDsParams struct {
	UserID   int64
	TopicIds []int64
}

func (q *Queries) DeleteUserTopicMutesByIDs(ctx context.Context, arg DeleteUserTopicMutesByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteUserTopicMutesByIDs, arg.UserID, arg.TopicIds)
	return err
}

const deleteUserTopics = `-- name: DeleteUserTopics :exec
DELETE FROM user_topics WHERE user_id = $1
`

func (q *Queries) DeleteUserTopics(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserTopics, userID)
	return err
}

const deleteUserTopicsByIDs = `-- name: DeleteUserTopicsByIDs :exec
DELETE FROM user_topics WHERE user_id = $1 AND topic_id = ANY($2::bigint[])
`

type DeleteUserTopicsByIDsParams struct {
	UserID   int64
	TopicIds []int64
}

func (q *Queries) DeleteUserTopicsByIDs(ctx context.Context, arg DeleteUserTopicsByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteUserTopicsByIDs, arg.UserID, arg.TopicIds)
	return err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email FROM users WHERE firebase_uid = $1
`

type GetUserByFirebaseUIDRow struct {
	ID          int64
	FirebaseUid string
	Email       *string
}

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (GetUserByFirebaseUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i GetUserByFirebaseUIDRow
	err := row.Scan(&i.ID, &i.FirebaseUid, &i.Email)
	return i, err
}

const getUserCountry = `-- name: GetUserCountry :one
SELECT country FROM users WHERE id = $1
`

func (q *Queries) GetUserCountry(ctx context.Context, userID int64) (*string, error) {
	row := q.db.QueryRow(ctx, getUserCountry, userID)
	var country *string
	err := row.Scan(&country)
	return country, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    (SELECT count(*) FROM user_bookmarks ub WHERE ub.user_id = $1)::bigint AS saved,
    (SELECT count(*) FROM user_story_state uss WHERE uss.user_id = $1)::bigint AS read
`

type GetUserStatsRow struct {
	Saved int64
	Read  int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID int64) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.Saved, &i.Read)
	return i, err
}

const insertUserProfessions = `-- name: InsertUserProfessions :exec
INSERT INTO user_professions (user_id, profession_id)
SELECT $1, unnest($2::bigint[])
`

type InsertUserProfessionsParams struct {
	UserID        int64
	ProfessionIds []int64
}

func (q *Queries) InsertUserProfessions(ctx context.Context, arg InsertUserProfessionsParams) error {
	_, err := q.db.Exec(ctx, insertUserProfessions, arg.UserID, arg.ProfessionIds)
	return err
}

const insertUserTopicMutes = `-- name: InsertUserTopicMutes :exec
INSERT INTO user_topic_mutes (user_id, topic_id)
SELECT $1, unnest($2::bigint[])
`

type InsertUserTopicMutesParams struct {
	UserID   int64
	TopicIds []int64
}

func (q *Queries) InsertUserTopicMutes(ctx context.Context, arg InsertUserTopicMutesParams) error {
	_, err := q.db.Exec(ctx, insertUserTopicMutes, arg.UserID, arg.TopicIds)
	return err
}

const insertUserTopics = `-- name: InsertUserTopics :exec
INSERT INTO user_topics (user_id, topic_id)
SELECT $1, unnest($2::bigint[])
`

type InsertUserTopicsParams struct {
	UserID   int64
	TopicIds []int64
}

func (q *Queries) InsertUserTopics(ctx context.Context, arg InsertUserTopicsParams) error {
	_, err := q.db.Exec(ctx, insertUserTopics, arg.UserID, arg.TopicIds)
	return err
}

const listUserMutedTopicSlugs = `-- name: ListUserMutedTopicSlugs :many
SELECT t.slug
FROM user_topic_mutes um
JOIN topics t ON t.id = um.topic_id
WHERE um.user_id = $1
ORDER BY t.slug
`

func (q *Queries) ListUserMutedTopicSlugs(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserMutedTopicSlugs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProfessionSlugs = `-- name: ListUserProfessionSlugs :many
SELECT p.slug
FROM user_professions up
JOIN professions p ON p.id = up.profession_id
WHERE up.user_id = $1
ORDER BY p.position, p.slug
`

func (q *Queries) ListUserProfessionSlugs(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserProfessionSlugs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTopicSlugs = `-- name: ListUserTopicSlugs :many
SELECT t.slug
FROM user_topics ut
JOIN topics t ON t.id = ut.topic_id
WHERE ut.user_id = $1
ORDER BY t.slug
`

func (q *Queries) ListUserTopicSlugs(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserTopicSlugs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCountry = `-- name: SetUserCountry :exec
UPDATE users SET country = $1 WHERE id = $2
`

type SetUserCountryParams struct {
	Country *string
	UserID  int64
}

func (q *Queries) SetUserCountry(ctx context.Context, arg SetUserCountryParams) error {
	_, err := q.db.Exec(ctx, setUserCountry, arg.Country, arg.UserID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (firebase_uid, email)
VALUES ($1, $2)
ON CONFLICT (firebase_uid) DO UPDATE SET email = COALESCE(EXCLUDED.email, users.email)
RETURNING id, firebase_uid, email
`

type UpsertUserParams struct {
	FirebaseUid string
	Email       *string
}

type UpsertUserRow struct {
	ID          int64
	FirebaseUid string
	Email       *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (UpsertUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.FirebaseUid, arg.Email)
	var i UpsertUserRow
	err := row.Scan(&i.ID, &i.FirebaseUid, &i.Email)
	return i, err
}
